package com.gsccs.b2c.plat.site.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gsccs.b2c.plat.bass.BaseExample;

public class AdvertExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public AdvertExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopid is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopid is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Long value) {
            addCriterion("shopid =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Long value) {
            addCriterion("shopid <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Long value) {
            addCriterion("shopid >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Long value) {
            addCriterion("shopid >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Long value) {
            addCriterion("shopid <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Long value) {
            addCriterion("shopid <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Long> values) {
            addCriterion("shopid in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Long> values) {
            addCriterion("shopid not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Long value1, Long value2) {
            addCriterion("shopid between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Long value1, Long value2) {
            addCriterion("shopid not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andSpaceidIsNull() {
            addCriterion("spaceid is null");
            return (Criteria) this;
        }

        public Criteria andSpaceidIsNotNull() {
            addCriterion("spaceid is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceidEqualTo(Long value) {
            addCriterion("spaceid =", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotEqualTo(Long value) {
            addCriterion("spaceid <>", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidGreaterThan(Long value) {
            addCriterion("spaceid >", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidGreaterThanOrEqualTo(Long value) {
            addCriterion("spaceid >=", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidLessThan(Long value) {
            addCriterion("spaceid <", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidLessThanOrEqualTo(Long value) {
            addCriterion("spaceid <=", value, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidIn(List<Long> values) {
            addCriterion("spaceid in", values, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotIn(List<Long> values) {
            addCriterion("spaceid not in", values, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidBetween(Long value1, Long value2) {
            addCriterion("spaceid between", value1, value2, "spaceid");
            return (Criteria) this;
        }

        public Criteria andSpaceidNotBetween(Long value1, Long value2) {
            addCriterion("spaceid not between", value1, value2, "spaceid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andAdvurlIsNull() {
            addCriterion("advurl is null");
            return (Criteria) this;
        }

        public Criteria andAdvurlIsNotNull() {
            addCriterion("advurl is not null");
            return (Criteria) this;
        }

        public Criteria andAdvurlEqualTo(String value) {
            addCriterion("advurl =", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlNotEqualTo(String value) {
            addCriterion("advurl <>", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlGreaterThan(String value) {
            addCriterion("advurl >", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlGreaterThanOrEqualTo(String value) {
            addCriterion("advurl >=", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlLessThan(String value) {
            addCriterion("advurl <", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlLessThanOrEqualTo(String value) {
            addCriterion("advurl <=", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlLike(String value) {
            addCriterion("advurl like", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlNotLike(String value) {
            addCriterion("advurl not like", value, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlIn(List<String> values) {
            addCriterion("advurl in", values, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlNotIn(List<String> values) {
            addCriterion("advurl not in", values, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlBetween(String value1, String value2) {
            addCriterion("advurl between", value1, value2, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvurlNotBetween(String value1, String value2) {
            addCriterion("advurl not between", value1, value2, "advurl");
            return (Criteria) this;
        }

        public Criteria andAdvimgIsNull() {
            addCriterion("advimg is null");
            return (Criteria) this;
        }

        public Criteria andAdvimgIsNotNull() {
            addCriterion("advimg is not null");
            return (Criteria) this;
        }

        public Criteria andAdvimgEqualTo(String value) {
            addCriterion("advimg =", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgNotEqualTo(String value) {
            addCriterion("advimg <>", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgGreaterThan(String value) {
            addCriterion("advimg >", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgGreaterThanOrEqualTo(String value) {
            addCriterion("advimg >=", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgLessThan(String value) {
            addCriterion("advimg <", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgLessThanOrEqualTo(String value) {
            addCriterion("advimg <=", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgLike(String value) {
            addCriterion("advimg like", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgNotLike(String value) {
            addCriterion("advimg not like", value, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgIn(List<String> values) {
            addCriterion("advimg in", values, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgNotIn(List<String> values) {
            addCriterion("advimg not in", values, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgBetween(String value1, String value2) {
            addCriterion("advimg between", value1, value2, "advimg");
            return (Criteria) this;
        }

        public Criteria andAdvimgNotBetween(String value1, String value2) {
            addCriterion("advimg not between", value1, value2, "advimg");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("starttime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("starttime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("starttime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("starttime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("starttime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starttime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("starttime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("starttime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("starttime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("starttime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("starttime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("starttime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andOrdernumIsNull() {
            addCriterion("ordernum is null");
            return (Criteria) this;
        }

        public Criteria andOrdernumIsNotNull() {
            addCriterion("ordernum is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernumEqualTo(Integer value) {
            addCriterion("ordernum =", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumNotEqualTo(Integer value) {
            addCriterion("ordernum <>", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumGreaterThan(Integer value) {
            addCriterion("ordernum >", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordernum >=", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumLessThan(Integer value) {
            addCriterion("ordernum <", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumLessThanOrEqualTo(Integer value) {
            addCriterion("ordernum <=", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumIn(List<Integer> values) {
            addCriterion("ordernum in", values, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumNotIn(List<Integer> values) {
            addCriterion("ordernum not in", values, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumBetween(Integer value1, Integer value2) {
            addCriterion("ordernum between", value1, value2, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumNotBetween(Integer value1, Integer value2) {
            addCriterion("ordernum not between", value1, value2, "ordernum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_advert
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 13 11:29:58 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_advert
     *
     * @mbggenerated Sat Aug 13 11:29:58 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}