package com.gsccs.b2c.plat.site.model;

public class DbtableConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_dbtable_config.id
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_dbtable_config.key
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_dbtable_config.prefix
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_dbtable_config.title
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_dbtable_config.state
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dbtable_config.id
     *
     * @return the value of plat_dbtable_config.id
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dbtable_config.id
     *
     * @param id the value for plat_dbtable_config.id
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dbtable_config.key
     *
     * @return the value of plat_dbtable_config.key
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dbtable_config.key
     *
     * @param key the value for plat_dbtable_config.key
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dbtable_config.prefix
     *
     * @return the value of plat_dbtable_config.prefix
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dbtable_config.prefix
     *
     * @param prefix the value for plat_dbtable_config.prefix
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dbtable_config.title
     *
     * @return the value of plat_dbtable_config.title
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dbtable_config.title
     *
     * @param title the value for plat_dbtable_config.title
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_dbtable_config.state
     *
     * @return the value of plat_dbtable_config.state
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_dbtable_config.state
     *
     * @param state the value for plat_dbtable_config.state
     *
     * @mbggenerated Wed Mar 18 15:06:28 CST 2015
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}