package com.gsccs.b2c.plat.site.model;

import java.util.ArrayList;
import java.util.List;

import com.gsccs.b2c.plat.bass.BaseExample;

public class DeliverTypeTExample extends BaseExample {

	protected String orderByClause;
	protected boolean distinct;

	protected List<Criteria> oredCriteria;

	public DeliverTypeTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andCorpidIsNull() {
			addCriterion("corpid is null");
			return (Criteria) this;
		}

		public Criteria andCorpidIsNotNull() {
			addCriterion("corpid is not null");
			return (Criteria) this;
		}

		public Criteria andCorpidEqualTo(String value) {
			addCriterion("corpid =", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidNotEqualTo(String value) {
			addCriterion("corpid <>", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidGreaterThan(String value) {
			addCriterion("corpid >", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidGreaterThanOrEqualTo(String value) {
			addCriterion("corpid >=", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidLessThan(String value) {
			addCriterion("corpid <", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidLessThanOrEqualTo(String value) {
			addCriterion("corpid <=", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidLike(String value) {
			addCriterion("corpid like", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidNotLike(String value) {
			addCriterion("corpid not like", value, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidIn(List<String> values) {
			addCriterion("corpid in", values, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidNotIn(List<String> values) {
			addCriterion("corpid not in", values, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidBetween(String value1, String value2) {
			addCriterion("corpid between", value1, value2, "corpid");
			return (Criteria) this;
		}

		public Criteria andCorpidNotBetween(String value1, String value2) {
			addCriterion("corpid not between", value1, value2, "corpid");
			return (Criteria) this;
		}

		public Criteria andHascodIsNull() {
			addCriterion("hascod is null");
			return (Criteria) this;
		}

		public Criteria andHascodIsNotNull() {
			addCriterion("hascod is not null");
			return (Criteria) this;
		}

		public Criteria andHascodEqualTo(String value) {
			addCriterion("hascod =", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodNotEqualTo(String value) {
			addCriterion("hascod <>", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodGreaterThan(String value) {
			addCriterion("hascod >", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodGreaterThanOrEqualTo(String value) {
			addCriterion("hascod >=", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodLessThan(String value) {
			addCriterion("hascod <", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodLessThanOrEqualTo(String value) {
			addCriterion("hascod <=", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodLike(String value) {
			addCriterion("hascod like", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodNotLike(String value) {
			addCriterion("hascod not like", value, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodIn(List<String> values) {
			addCriterion("hascod in", values, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodNotIn(List<String> values) {
			addCriterion("hascod not in", values, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodBetween(String value1, String value2) {
			addCriterion("hascod between", value1, value2, "hascod");
			return (Criteria) this;
		}

		public Criteria andHascodNotBetween(String value1, String value2) {
			addCriterion("hascod not between", value1, value2, "hascod");
			return (Criteria) this;
		}

		public Criteria andFirstunitIsNull() {
			addCriterion("firstunit is null");
			return (Criteria) this;
		}

		public Criteria andFirstunitIsNotNull() {
			addCriterion("firstunit is not null");
			return (Criteria) this;
		}

		public Criteria andFirstunitEqualTo(Integer value) {
			addCriterion("firstunit =", value, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitNotEqualTo(Integer value) {
			addCriterion("firstunit <>", value, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitGreaterThan(Integer value) {
			addCriterion("firstunit >", value, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitGreaterThanOrEqualTo(Integer value) {
			addCriterion("firstunit >=", value, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitLessThan(Integer value) {
			addCriterion("firstunit <", value, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitLessThanOrEqualTo(Integer value) {
			addCriterion("firstunit <=", value, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitIn(List<Integer> values) {
			addCriterion("firstunit in", values, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitNotIn(List<Integer> values) {
			addCriterion("firstunit not in", values, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitBetween(Integer value1, Integer value2) {
			addCriterion("firstunit between", value1, value2, "firstunit");
			return (Criteria) this;
		}

		public Criteria andFirstunitNotBetween(Integer value1, Integer value2) {
			addCriterion("firstunit not between", value1, value2, "firstunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitIsNull() {
			addCriterion("continueunit is null");
			return (Criteria) this;
		}

		public Criteria andContinueunitIsNotNull() {
			addCriterion("continueunit is not null");
			return (Criteria) this;
		}

		public Criteria andContinueunitEqualTo(Integer value) {
			addCriterion("continueunit =", value, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitNotEqualTo(Integer value) {
			addCriterion("continueunit <>", value, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitGreaterThan(Integer value) {
			addCriterion("continueunit >", value, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitGreaterThanOrEqualTo(Integer value) {
			addCriterion("continueunit >=", value, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitLessThan(Integer value) {
			addCriterion("continueunit <", value, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitLessThanOrEqualTo(Integer value) {
			addCriterion("continueunit <=", value, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitIn(List<Integer> values) {
			addCriterion("continueunit in", values, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitNotIn(List<Integer> values) {
			addCriterion("continueunit not in", values, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitBetween(Integer value1, Integer value2) {
			addCriterion("continueunit between", value1, value2, "continueunit");
			return (Criteria) this;
		}

		public Criteria andContinueunitNotBetween(Integer value1, Integer value2) {
			addCriterion("continueunit not between", value1, value2,
					"continueunit");
			return (Criteria) this;
		}

		public Criteria andFirstpriceIsNull() {
			addCriterion("firstprice is null");
			return (Criteria) this;
		}

		public Criteria andFirstpriceIsNotNull() {
			addCriterion("firstprice is not null");
			return (Criteria) this;
		}

		public Criteria andFirstpriceEqualTo(Float value) {
			addCriterion("firstprice =", value, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceNotEqualTo(Float value) {
			addCriterion("firstprice <>", value, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceGreaterThan(Float value) {
			addCriterion("firstprice >", value, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceGreaterThanOrEqualTo(Float value) {
			addCriterion("firstprice >=", value, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceLessThan(Float value) {
			addCriterion("firstprice <", value, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceLessThanOrEqualTo(Float value) {
			addCriterion("firstprice <=", value, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceIn(List<Float> values) {
			addCriterion("firstprice in", values, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceNotIn(List<Float> values) {
			addCriterion("firstprice not in", values, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceBetween(Float value1, Float value2) {
			addCriterion("firstprice between", value1, value2, "firstprice");
			return (Criteria) this;
		}

		public Criteria andFirstpriceNotBetween(Float value1, Float value2) {
			addCriterion("firstprice not between", value1, value2, "firstprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceIsNull() {
			addCriterion("continueprice is null");
			return (Criteria) this;
		}

		public Criteria andContinuepriceIsNotNull() {
			addCriterion("continueprice is not null");
			return (Criteria) this;
		}

		public Criteria andContinuepriceEqualTo(Float value) {
			addCriterion("continueprice =", value, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceNotEqualTo(Float value) {
			addCriterion("continueprice <>", value, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceGreaterThan(Float value) {
			addCriterion("continueprice >", value, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceGreaterThanOrEqualTo(Float value) {
			addCriterion("continueprice >=", value, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceLessThan(Float value) {
			addCriterion("continueprice <", value, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceLessThanOrEqualTo(Float value) {
			addCriterion("continueprice <=", value, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceIn(List<Float> values) {
			addCriterion("continueprice in", values, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceNotIn(List<Float> values) {
			addCriterion("continueprice not in", values, "continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceBetween(Float value1, Float value2) {
			addCriterion("continueprice between", value1, value2,
					"continueprice");
			return (Criteria) this;
		}

		public Criteria andContinuepriceNotBetween(Float value1, Float value2) {
			addCriterion("continueprice not between", value1, value2,
					"continueprice");
			return (Criteria) this;
		}

		public Criteria andExpressionsIsNull() {
			addCriterion("expressions is null");
			return (Criteria) this;
		}

		public Criteria andExpressionsIsNotNull() {
			addCriterion("expressions is not null");
			return (Criteria) this;
		}

		public Criteria andExpressionsEqualTo(String value) {
			addCriterion("expressions =", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsNotEqualTo(String value) {
			addCriterion("expressions <>", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsGreaterThan(String value) {
			addCriterion("expressions >", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsGreaterThanOrEqualTo(String value) {
			addCriterion("expressions >=", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsLessThan(String value) {
			addCriterion("expressions <", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsLessThanOrEqualTo(String value) {
			addCriterion("expressions <=", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsLike(String value) {
			addCriterion("expressions like", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsNotLike(String value) {
			addCriterion("expressions not like", value, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsIn(List<String> values) {
			addCriterion("expressions in", values, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsNotIn(List<String> values) {
			addCriterion("expressions not in", values, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsBetween(String value1, String value2) {
			addCriterion("expressions between", value1, value2, "expressions");
			return (Criteria) this;
		}

		public Criteria andExpressionsNotBetween(String value1, String value2) {
			addCriterion("expressions not between", value1, value2,
					"expressions");
			return (Criteria) this;
		}

		public Criteria andProtectIsNull() {
			addCriterion("protect is null");
			return (Criteria) this;
		}

		public Criteria andProtectIsNotNull() {
			addCriterion("protect is not null");
			return (Criteria) this;
		}

		public Criteria andProtectEqualTo(String value) {
			addCriterion("protect =", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectNotEqualTo(String value) {
			addCriterion("protect <>", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectGreaterThan(String value) {
			addCriterion("protect >", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectGreaterThanOrEqualTo(String value) {
			addCriterion("protect >=", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectLessThan(String value) {
			addCriterion("protect <", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectLessThanOrEqualTo(String value) {
			addCriterion("protect <=", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectLike(String value) {
			addCriterion("protect like", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectNotLike(String value) {
			addCriterion("protect not like", value, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectIn(List<String> values) {
			addCriterion("protect in", values, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectNotIn(List<String> values) {
			addCriterion("protect not in", values, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectBetween(String value1, String value2) {
			addCriterion("protect between", value1, value2, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectNotBetween(String value1, String value2) {
			addCriterion("protect not between", value1, value2, "protect");
			return (Criteria) this;
		}

		public Criteria andProtectRateIsNull() {
			addCriterion("protect_rate is null");
			return (Criteria) this;
		}

		public Criteria andProtectRateIsNotNull() {
			addCriterion("protect_rate is not null");
			return (Criteria) this;
		}

		public Criteria andProtectRateEqualTo(Float value) {
			addCriterion("protect_rate =", value, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateNotEqualTo(Float value) {
			addCriterion("protect_rate <>", value, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateGreaterThan(Float value) {
			addCriterion("protect_rate >", value, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateGreaterThanOrEqualTo(Float value) {
			addCriterion("protect_rate >=", value, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateLessThan(Float value) {
			addCriterion("protect_rate <", value, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateLessThanOrEqualTo(Float value) {
			addCriterion("protect_rate <=", value, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateIn(List<Float> values) {
			addCriterion("protect_rate in", values, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateNotIn(List<Float> values) {
			addCriterion("protect_rate not in", values, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateBetween(Float value1, Float value2) {
			addCriterion("protect_rate between", value1, value2, "protectRate");
			return (Criteria) this;
		}

		public Criteria andProtectRateNotBetween(Float value1, Float value2) {
			addCriterion("protect_rate not between", value1, value2,
					"protectRate");
			return (Criteria) this;
		}

		public Criteria andMinpriceIsNull() {
			addCriterion("minprice is null");
			return (Criteria) this;
		}

		public Criteria andMinpriceIsNotNull() {
			addCriterion("minprice is not null");
			return (Criteria) this;
		}

		public Criteria andMinpriceEqualTo(Float value) {
			addCriterion("minprice =", value, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceNotEqualTo(Float value) {
			addCriterion("minprice <>", value, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceGreaterThan(Float value) {
			addCriterion("minprice >", value, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceGreaterThanOrEqualTo(Float value) {
			addCriterion("minprice >=", value, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceLessThan(Float value) {
			addCriterion("minprice <", value, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceLessThanOrEqualTo(Float value) {
			addCriterion("minprice <=", value, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceIn(List<Float> values) {
			addCriterion("minprice in", values, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceNotIn(List<Float> values) {
			addCriterion("minprice not in", values, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceBetween(Float value1, Float value2) {
			addCriterion("minprice between", value1, value2, "minprice");
			return (Criteria) this;
		}

		public Criteria andMinpriceNotBetween(Float value1, Float value2) {
			addCriterion("minprice not between", value1, value2, "minprice");
			return (Criteria) this;
		}

		public Criteria andSettingIsNull() {
			addCriterion("setting is null");
			return (Criteria) this;
		}

		public Criteria andSettingIsNotNull() {
			addCriterion("setting is not null");
			return (Criteria) this;
		}

		public Criteria andSettingEqualTo(String value) {
			addCriterion("setting =", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingNotEqualTo(String value) {
			addCriterion("setting <>", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingGreaterThan(String value) {
			addCriterion("setting >", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingGreaterThanOrEqualTo(String value) {
			addCriterion("setting >=", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingLessThan(String value) {
			addCriterion("setting <", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingLessThanOrEqualTo(String value) {
			addCriterion("setting <=", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingLike(String value) {
			addCriterion("setting like", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingNotLike(String value) {
			addCriterion("setting not like", value, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingIn(List<String> values) {
			addCriterion("setting in", values, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingNotIn(List<String> values) {
			addCriterion("setting not in", values, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingBetween(String value1, String value2) {
			addCriterion("setting between", value1, value2, "setting");
			return (Criteria) this;
		}

		public Criteria andSettingNotBetween(String value1, String value2) {
			addCriterion("setting not between", value1, value2, "setting");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNull() {
			addCriterion("ordernum is null");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNotNull() {
			addCriterion("ordernum is not null");
			return (Criteria) this;
		}

		public Criteria andOrdernumEqualTo(String value) {
			addCriterion("ordernum =", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotEqualTo(String value) {
			addCriterion("ordernum <>", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThan(String value) {
			addCriterion("ordernum >", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThanOrEqualTo(String value) {
			addCriterion("ordernum >=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThan(String value) {
			addCriterion("ordernum <", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThanOrEqualTo(String value) {
			addCriterion("ordernum <=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLike(String value) {
			addCriterion("ordernum like", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotLike(String value) {
			addCriterion("ordernum not like", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumIn(List<String> values) {
			addCriterion("ordernum in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotIn(List<String> values) {
			addCriterion("ordernum not in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumBetween(String value1, String value2) {
			addCriterion("ordernum between", value1, value2, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotBetween(String value1, String value2) {
			addCriterion("ordernum not between", value1, value2, "ordernum");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSiteidIsNull() {
			addCriterion("siteid is null");
			return (Criteria) this;
		}

		public Criteria andSiteidIsNotNull() {
			addCriterion("siteid is not null");
			return (Criteria) this;
		}

		public Criteria andSiteidEqualTo(Long value) {
			addCriterion("siteid =", value, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidNotEqualTo(Long value) {
			addCriterion("siteid <>", value, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidGreaterThan(Long value) {
			addCriterion("siteid >", value, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidGreaterThanOrEqualTo(Long value) {
			addCriterion("siteid >=", value, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidLessThan(Long value) {
			addCriterion("siteid <", value, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidLessThanOrEqualTo(Long value) {
			addCriterion("siteid <=", value, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidIn(List<Long> values) {
			addCriterion("siteid in", values, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidNotIn(List<Long> values) {
			addCriterion("siteid not in", values, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidBetween(Long value1, Long value2) {
			addCriterion("siteid between", value1, value2, "siteid");
			return (Criteria) this;
		}

		public Criteria andSiteidNotBetween(Long value1, Long value2) {
			addCriterion("siteid not between", value1, value2, "siteid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table plat_deliver_type
	 * 
	 * @mbggenerated do_not_delete_during_merge Fri Jun 05 14:47:54 CST 2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}