package com.gsccs.b2c.plat.site.model;

/**
 * 商城Banner
 * @author x.d zhang
 *
 */
public class StoreyBanner {

	private String id;
	private String title;
	private String imgurl;
	private String link;
	private String type;
	private Long siteid;
	private Integer ordernum;

	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.id
	 * 
	 * @param id
	 *            the value for site_storey_banner.id
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column site_storey_banner.title
	 * 
	 * @return the value of site_storey_banner.title
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.title
	 * 
	 * @param title
	 *            the value for site_storey_banner.title
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column site_storey_banner.imgurl
	 * 
	 * @return the value of site_storey_banner.imgurl
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public String getImgurl() {
		return imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.imgurl
	 * 
	 * @param imgurl
	 *            the value for site_storey_banner.imgurl
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setImgurl(String imgurl) {
		this.imgurl = imgurl == null ? null : imgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column site_storey_banner.link
	 * 
	 * @return the value of site_storey_banner.link
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.link
	 * 
	 * @param link
	 *            the value for site_storey_banner.link
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setLink(String link) {
		this.link = link == null ? null : link.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column site_storey_banner.type
	 * 
	 * @return the value of site_storey_banner.type
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.type
	 * 
	 * @param type
	 *            the value for site_storey_banner.type
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column site_storey_banner.siteid
	 * 
	 * @return the value of site_storey_banner.siteid
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public Long getSiteid() {
		return siteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.siteid
	 * 
	 * @param siteid
	 *            the value for site_storey_banner.siteid
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setSiteid(Long siteid) {
		this.siteid = siteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column site_storey_banner.ordernum
	 * 
	 * @return the value of site_storey_banner.ordernum
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public Integer getOrdernum() {
		return ordernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_storey_banner.ordernum
	 * 
	 * @param ordernum
	 *            the value for site_storey_banner.ordernum
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	public void setOrdernum(Integer ordernum) {
		this.ordernum = ordernum;
	}
}