package com.gsccs.b2c.plat.site.model;

/**
 * 商城单个楼层对象
 * @author x.d zhang
 *
 */
public class StoreyItem {
    
    private String id;
    private String title;
    private String link;
    private String imgurl;
    private String type;
    private String storeyid;
    private Long siteid;
    private Integer ordernum = 0;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_item.id
     *
     * @param id the value for site_storey_item.id
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_item.title
     *
     * @return the value of site_storey_item.title
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_item.title
     *
     * @param title the value for site_storey_item.title
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_item.link
     *
     * @return the value of site_storey_item.link
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_item.link
     *
     * @param link the value for site_storey_item.link
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_item.imgurl
     *
     * @return the value of site_storey_item.imgurl
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_item.imgurl
     *
     * @param imgurl the value for site_storey_item.imgurl
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_item.type
     *
     * @return the value of site_storey_item.type
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_item.type
     *
     * @param type the value for site_storey_item.type
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_item.storeyid
     *
     * @return the value of site_storey_item.storeyid
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getStoreyid() {
        return storeyid;
    }

  
    public void setStoreyid(String storeyid) {
        this.storeyid = storeyid == null ? null : storeyid.trim();
    }

    
    public Long getSiteid() {
        return siteid;
    }

   
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }

	public Integer getOrdernum() {
		return ordernum;
	}

	public void setOrdernum(Integer ordernum) {
		this.ordernum = ordernum;
	}
    
    
}