package com.gsccs.b2c.plat.site.model;


/**
 * 商城楼层列表对象
 * @author x.d zhang
 *
 */
public class StoreyList {
    
    private String id;
    private String title;
    private String link;
    private String icon;
    private String bgcolor;
    private String mainimg;
    private String mainlink;
    private Integer ordernum;
    private Long siteid;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.id
     *
     * @param id the value for site_storey_list.id
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.title
     *
     * @return the value of site_storey_list.title
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.title
     *
     * @param title the value for site_storey_list.title
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.link
     *
     * @return the value of site_storey_list.link
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.link
     *
     * @param link the value for site_storey_list.link
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.icon
     *
     * @return the value of site_storey_list.icon
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.icon
     *
     * @param icon the value for site_storey_list.icon
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.bgcolor
     *
     * @return the value of site_storey_list.bgcolor
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.bgcolor
     *
     * @param bgcolor the value for site_storey_list.bgcolor
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setBgcolor(String bgcolor) {
        this.bgcolor = bgcolor == null ? null : bgcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.mainimg
     *
     * @return the value of site_storey_list.mainimg
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getMainimg() {
        return mainimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.mainimg
     *
     * @param mainimg the value for site_storey_list.mainimg
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setMainimg(String mainimg) {
        this.mainimg = mainimg == null ? null : mainimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.mainlink
     *
     * @return the value of site_storey_list.mainlink
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public String getMainlink() {
        return mainlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.mainlink
     *
     * @param mainlink the value for site_storey_list.mainlink
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setMainlink(String mainlink) {
        this.mainlink = mainlink == null ? null : mainlink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.ordernum
     *
     * @return the value of site_storey_list.ordernum
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.ordernum
     *
     * @param ordernum the value for site_storey_list.ordernum
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_storey_list.siteid
     *
     * @return the value of site_storey_list.siteid
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public Long getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_storey_list.siteid
     *
     * @param siteid the value for site_storey_list.siteid
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }
}