package com.gsccs.b2c.plat.shop.model;

public class BuyerLevelT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.id
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.name
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.experience
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.isdefault
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private String isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.point
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.dis_count
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private Float disCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_buyer_level.site_id
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    private Long siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.id
     *
     * @return the value of shop_buyer_level.id
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.id
     *
     * @param id the value for shop_buyer_level.id
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.name
     *
     * @return the value of shop_buyer_level.name
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.name
     *
     * @param name the value for shop_buyer_level.name
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.experience
     *
     * @return the value of shop_buyer_level.experience
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.experience
     *
     * @param experience the value for shop_buyer_level.experience
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.isdefault
     *
     * @return the value of shop_buyer_level.isdefault
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public String getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.isdefault
     *
     * @param isdefault the value for shop_buyer_level.isdefault
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault == null ? null : isdefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.point
     *
     * @return the value of shop_buyer_level.point
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.point
     *
     * @param point the value for shop_buyer_level.point
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.dis_count
     *
     * @return the value of shop_buyer_level.dis_count
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public Float getDisCount() {
        return disCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.dis_count
     *
     * @param disCount the value for shop_buyer_level.dis_count
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setDisCount(Float disCount) {
        this.disCount = disCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_buyer_level.site_id
     *
     * @return the value of shop_buyer_level.site_id
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_buyer_level.site_id
     *
     * @param siteId the value for shop_buyer_level.site_id
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }
}