package com.gsccs.b2c.plat.shop.model;

import java.util.Date;

public class CollectT {
    private String id;
    private String targetid;
    private String colltype;
    private Long buyerid;
    private Date addtime;
    private Long siteid;
    private String remark;
    private String picurl;

    
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getTargetid() {
        return targetid;
    }

    public void setTargetid(String targetid) {
        this.targetid = targetid == null ? null : targetid.trim();
    }

   
    public Long getBuyerid() {
        return buyerid;
    }

    public void setBuyerid(Long buyerid) {
        this.buyerid = buyerid;
    }

    public Date getAddtime() {
        return addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_collect.siteid
     *
     * @return the value of shop_collect.siteid
     *
     * @mbggenerated Sat Nov 14 13:51:48 CST 2015
     */
    public Long getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_collect.siteid
     *
     * @param siteid the value for shop_collect.siteid
     *
     * @mbggenerated Sat Nov 14 13:51:48 CST 2015
     */
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_collect.remark
     *
     * @return the value of shop_collect.remark
     *
     * @mbggenerated Sat Nov 14 13:51:48 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getPicurl() {
        return picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

	public String getColltype() {
		return colltype;
	}

	public void setColltype(String colltype) {
		this.colltype = colltype;
	}
}