package com.gsccs.b2c.plat.shop.model;

import java.util.ArrayList;
import java.util.List;

public class EvalConfTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public EvalConfTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsopenIsNull() {
            addCriterion("isopen is null");
            return (Criteria) this;
        }

        public Criteria andIsopenIsNotNull() {
            addCriterion("isopen is not null");
            return (Criteria) this;
        }

        public Criteria andIsopenEqualTo(String value) {
            addCriterion("isopen =", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotEqualTo(String value) {
            addCriterion("isopen <>", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenGreaterThan(String value) {
            addCriterion("isopen >", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenGreaterThanOrEqualTo(String value) {
            addCriterion("isopen >=", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenLessThan(String value) {
            addCriterion("isopen <", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenLessThanOrEqualTo(String value) {
            addCriterion("isopen <=", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenLike(String value) {
            addCriterion("isopen like", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotLike(String value) {
            addCriterion("isopen not like", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenIn(List<String> values) {
            addCriterion("isopen in", values, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotIn(List<String> values) {
            addCriterion("isopen not in", values, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenBetween(String value1, String value2) {
            addCriterion("isopen between", value1, value2, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotBetween(String value1, String value2) {
            addCriterion("isopen not between", value1, value2, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsdefaultIsNull() {
            addCriterion("isdefault is null");
            return (Criteria) this;
        }

        public Criteria andIsdefaultIsNotNull() {
            addCriterion("isdefault is not null");
            return (Criteria) this;
        }

        public Criteria andIsdefaultEqualTo(String value) {
            addCriterion("isdefault =", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultNotEqualTo(String value) {
            addCriterion("isdefault <>", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultGreaterThan(String value) {
            addCriterion("isdefault >", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultGreaterThanOrEqualTo(String value) {
            addCriterion("isdefault >=", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultLessThan(String value) {
            addCriterion("isdefault <", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultLessThanOrEqualTo(String value) {
            addCriterion("isdefault <=", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultLike(String value) {
            addCriterion("isdefault like", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultNotLike(String value) {
            addCriterion("isdefault not like", value, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultIn(List<String> values) {
            addCriterion("isdefault in", values, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultNotIn(List<String> values) {
            addCriterion("isdefault not in", values, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultBetween(String value1, String value2) {
            addCriterion("isdefault between", value1, value2, "isdefault");
            return (Criteria) this;
        }

        public Criteria andIsdefaultNotBetween(String value1, String value2) {
            addCriterion("isdefault not between", value1, value2, "isdefault");
            return (Criteria) this;
        }

        public Criteria andWaitingIsNull() {
            addCriterion("waiting is null");
            return (Criteria) this;
        }

        public Criteria andWaitingIsNotNull() {
            addCriterion("waiting is not null");
            return (Criteria) this;
        }

        public Criteria andWaitingEqualTo(String value) {
            addCriterion("waiting =", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingNotEqualTo(String value) {
            addCriterion("waiting <>", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingGreaterThan(String value) {
            addCriterion("waiting >", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingGreaterThanOrEqualTo(String value) {
            addCriterion("waiting >=", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingLessThan(String value) {
            addCriterion("waiting <", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingLessThanOrEqualTo(String value) {
            addCriterion("waiting <=", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingLike(String value) {
            addCriterion("waiting like", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingNotLike(String value) {
            addCriterion("waiting not like", value, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingIn(List<String> values) {
            addCriterion("waiting in", values, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingNotIn(List<String> values) {
            addCriterion("waiting not in", values, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingBetween(String value1, String value2) {
            addCriterion("waiting between", value1, value2, "waiting");
            return (Criteria) this;
        }

        public Criteria andWaitingNotBetween(String value1, String value2) {
            addCriterion("waiting not between", value1, value2, "waiting");
            return (Criteria) this;
        }

        public Criteria andDisplayIsNull() {
            addCriterion("display is null");
            return (Criteria) this;
        }

        public Criteria andDisplayIsNotNull() {
            addCriterion("display is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayEqualTo(String value) {
            addCriterion("display =", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayNotEqualTo(String value) {
            addCriterion("display <>", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayGreaterThan(String value) {
            addCriterion("display >", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayGreaterThanOrEqualTo(String value) {
            addCriterion("display >=", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayLessThan(String value) {
            addCriterion("display <", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayLessThanOrEqualTo(String value) {
            addCriterion("display <=", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayLike(String value) {
            addCriterion("display like", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayNotLike(String value) {
            addCriterion("display not like", value, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayIn(List<String> values) {
            addCriterion("display in", values, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayNotIn(List<String> values) {
            addCriterion("display not in", values, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayBetween(String value1, String value2) {
            addCriterion("display between", value1, value2, "display");
            return (Criteria) this;
        }

        public Criteria andDisplayNotBetween(String value1, String value2) {
            addCriterion("display not between", value1, value2, "display");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andDiscussIsNull() {
            addCriterion("discuss is null");
            return (Criteria) this;
        }

        public Criteria andDiscussIsNotNull() {
            addCriterion("discuss is not null");
            return (Criteria) this;
        }

        public Criteria andDiscussEqualTo(String value) {
            addCriterion("discuss =", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussNotEqualTo(String value) {
            addCriterion("discuss <>", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussGreaterThan(String value) {
            addCriterion("discuss >", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussGreaterThanOrEqualTo(String value) {
            addCriterion("discuss >=", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussLessThan(String value) {
            addCriterion("discuss <", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussLessThanOrEqualTo(String value) {
            addCriterion("discuss <=", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussLike(String value) {
            addCriterion("discuss like", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussNotLike(String value) {
            addCriterion("discuss not like", value, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussIn(List<String> values) {
            addCriterion("discuss in", values, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussNotIn(List<String> values) {
            addCriterion("discuss not in", values, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussBetween(String value1, String value2) {
            addCriterion("discuss between", value1, value2, "discuss");
            return (Criteria) this;
        }

        public Criteria andDiscussNotBetween(String value1, String value2) {
            addCriterion("discuss not between", value1, value2, "discuss");
            return (Criteria) this;
        }

        public Criteria andPointstatusIsNull() {
            addCriterion("pointstatus is null");
            return (Criteria) this;
        }

        public Criteria andPointstatusIsNotNull() {
            addCriterion("pointstatus is not null");
            return (Criteria) this;
        }

        public Criteria andPointstatusEqualTo(String value) {
            addCriterion("pointstatus =", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusNotEqualTo(String value) {
            addCriterion("pointstatus <>", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusGreaterThan(String value) {
            addCriterion("pointstatus >", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusGreaterThanOrEqualTo(String value) {
            addCriterion("pointstatus >=", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusLessThan(String value) {
            addCriterion("pointstatus <", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusLessThanOrEqualTo(String value) {
            addCriterion("pointstatus <=", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusLike(String value) {
            addCriterion("pointstatus like", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusNotLike(String value) {
            addCriterion("pointstatus not like", value, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusIn(List<String> values) {
            addCriterion("pointstatus in", values, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusNotIn(List<String> values) {
            addCriterion("pointstatus not in", values, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusBetween(String value1, String value2) {
            addCriterion("pointstatus between", value1, value2, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andPointstatusNotBetween(String value1, String value2) {
            addCriterion("pointstatus not between", value1, value2, "pointstatus");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNull() {
            addCriterion("siteid is null");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNotNull() {
            addCriterion("siteid is not null");
            return (Criteria) this;
        }

        public Criteria andSiteidEqualTo(Long value) {
            addCriterion("siteid =", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotEqualTo(Long value) {
            addCriterion("siteid <>", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThan(Long value) {
            addCriterion("siteid >", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThanOrEqualTo(Long value) {
            addCriterion("siteid >=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThan(Long value) {
            addCriterion("siteid <", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThanOrEqualTo(Long value) {
            addCriterion("siteid <=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidIn(List<Long> values) {
            addCriterion("siteid in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotIn(List<Long> values) {
            addCriterion("siteid not in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidBetween(Long value1, Long value2) {
            addCriterion("siteid between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotBetween(Long value1, Long value2) {
            addCriterion("siteid not between", value1, value2, "siteid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_eval_conf
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 24 16:46:49 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_eval_conf
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}