package com.gsccs.b2c.plat.shop.model;

public class EvalConfT {
   
    private Long id;
    private String isopen;
    private String isdefault;
    private String waiting;
    private String display;
    private String comment;
    private String discuss;
    private String pointstatus;
    private Long siteid;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.id
     *
     * @param id the value for shop_eval_conf.id
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.isopen
     *
     * @return the value of shop_eval_conf.isopen
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getIsopen() {
        return isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.isopen
     *
     * @param isopen the value for shop_eval_conf.isopen
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setIsopen(String isopen) {
        this.isopen = isopen == null ? null : isopen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.isdefault
     *
     * @return the value of shop_eval_conf.isdefault
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.isdefault
     *
     * @param isdefault the value for shop_eval_conf.isdefault
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault == null ? null : isdefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.waiting
     *
     * @return the value of shop_eval_conf.waiting
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getWaiting() {
        return waiting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.waiting
     *
     * @param waiting the value for shop_eval_conf.waiting
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setWaiting(String waiting) {
        this.waiting = waiting == null ? null : waiting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.display
     *
     * @return the value of shop_eval_conf.display
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.display
     *
     * @param display the value for shop_eval_conf.display
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setDisplay(String display) {
        this.display = display == null ? null : display.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.comment
     *
     * @return the value of shop_eval_conf.comment
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.comment
     *
     * @param comment the value for shop_eval_conf.comment
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.discuss
     *
     * @return the value of shop_eval_conf.discuss
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getDiscuss() {
        return discuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.discuss
     *
     * @param discuss the value for shop_eval_conf.discuss
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setDiscuss(String discuss) {
        this.discuss = discuss == null ? null : discuss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.pointstatus
     *
     * @return the value of shop_eval_conf.pointstatus
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getPointstatus() {
        return pointstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.pointstatus
     *
     * @param pointstatus the value for shop_eval_conf.pointstatus
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setPointstatus(String pointstatus) {
        this.pointstatus = pointstatus == null ? null : pointstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_eval_conf.siteid
     *
     * @return the value of shop_eval_conf.siteid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Long getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_eval_conf.siteid
     *
     * @param siteid the value for shop_eval_conf.siteid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }
}