package com.gsccs.b2c.plat.shop.model;


/**
 * 订单评分
 * @author x.d zhang
 *
 */
public class EvalOrderT {

	private Long id;
	private Long productid;
	private Long itemid;
	private Integer score;
	private Long userid;
	private String account;

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_evalscore_1001.id
	 * 
	 * @param id
	 *            the value for site_evalscore_1001.id
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	public Long getProductid() {
		return productid;
	}

	public void setProductid(Long productid) {
		this.productid = productid;
	}

	public Long getItemid() {
		return itemid;
	}

	public void setItemid(Long itemid) {
		this.itemid = itemid;
	}

	public Integer getScore() {
		return score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Long getUserid() {
		return userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column site_evalscore_1001.account
	 * 
	 * @param account
	 *            the value for site_evalscore_1001.account
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}
}