package com.gsccs.b2c.plat.shop.model;

public class RequirInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_reqinfo.id
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_reqinfo.label
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_reqinfo.type
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_reqinfo.options
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    private String options;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_reqinfo.type_id
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_reqinfo.orderNum
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    private Integer ordernum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_reqinfo.id
     *
     * @return the value of shop_reqinfo.id
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_reqinfo.id
     *
     * @param id the value for shop_reqinfo.id
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_reqinfo.label
     *
     * @return the value of shop_reqinfo.label
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_reqinfo.label
     *
     * @param label the value for shop_reqinfo.label
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_reqinfo.type
     *
     * @return the value of shop_reqinfo.type
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_reqinfo.type
     *
     * @param type the value for shop_reqinfo.type
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_reqinfo.options
     *
     * @return the value of shop_reqinfo.options
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_reqinfo.options
     *
     * @param options the value for shop_reqinfo.options
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_reqinfo.type_id
     *
     * @return the value of shop_reqinfo.type_id
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_reqinfo.type_id
     *
     * @param typeId the value for shop_reqinfo.type_id
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_reqinfo.orderNum
     *
     * @return the value of shop_reqinfo.orderNum
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_reqinfo.orderNum
     *
     * @param ordernum the value for shop_reqinfo.orderNum
     *
     * @mbggenerated Tue Mar 31 10:51:57 CST 2015
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }
}