package com.gsccs.b2c.plat.shop.model;

import java.util.ArrayList;
import java.util.List;

public class SkuSpecExample {

	protected String orderByClause;

	protected boolean distinct;

	protected List<Criteria> oredCriteria;

	public SkuSpecExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	public boolean isDistinct() {
		return distinct;
	}

	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_product_extra
	 * 
	 * @mbggenerated Mon Apr 13 09:58:08 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_product_extra
	 * 
	 * @mbggenerated Mon Apr 13 09:58:08 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_product_extra
	 * 
	 * @mbggenerated Mon Apr 13 09:58:08 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPropsstrIsNull() {
			addCriterion("specid is null");
			return (Criteria) this;
		}

		public Criteria andPropsstrIsNotNull() {
			addCriterion("specid is not null");
			return (Criteria) this;
		}

		public Criteria andPropsstrEqualTo(String value) {
			addCriterion("specid =", value, "propsstr");
			return (Criteria) this;
		}

		public Criteria andPropsstrNotEqualTo(String value) {
			addCriterion("specid <>", value, "propsstr");
			return (Criteria) this;
		}

		public Criteria andPropsstrIn(List<String> values) {
			addCriterion("specid in", values, "propsstr");
			return (Criteria) this;
		}

		public Criteria andPropsstrNotIn(List<String> values) {
			addCriterion("specid not in", values, "propsstr");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNull() {
			addCriterion("goodsid is null");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNotNull() {
			addCriterion("goodsid is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsidEqualTo(Long value) {
			addCriterion("goodsid =", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotEqualTo(Long value) {
			addCriterion("goodsid <>", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidIn(List<Long> values) {
			addCriterion("goodsid in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotIn(List<String> values) {
			addCriterion("goodsid not in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andSkuidIsNull() {
			addCriterion("skuid is null");
			return (Criteria) this;
		}

		public Criteria andSkuidIsNotNull() {
			addCriterion("skuid is not null");
			return (Criteria) this;
		}

		public Criteria andSkuidEqualTo(Long value) {
			addCriterion("skuid =", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidNotEqualTo(Long value) {
			addCriterion("skuid <>", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidIn(List<Long> values) {
			addCriterion("skuid in", values, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidNotIn(List<Long> values) {
			addCriterion("skuid not in", values, "skuid");
			return (Criteria) this;
		}

	}

	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}