package com.gsccs.b2c.plat.shop.model;

public class StoreNavT {

	private String id;
	private String title;
	private String href;
	private String iscate;
	private Long cateid;
	private String blank;
	private String state;
	private Long siteid;

	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.id
	 * 
	 * @param id
	 *            the value for shop_store_nav.id
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_store_nav.title
	 * 
	 * @return the value of shop_store_nav.title
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.title
	 * 
	 * @param title
	 *            the value for shop_store_nav.title
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_store_nav.href
	 * 
	 * @return the value of shop_store_nav.href
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public String getHref() {
		return href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.href
	 * 
	 * @param href
	 *            the value for shop_store_nav.href
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setHref(String href) {
		this.href = href == null ? null : href.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_store_nav.iscate
	 * 
	 * @return the value of shop_store_nav.iscate
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public String getIscate() {
		return iscate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.iscate
	 * 
	 * @param iscate
	 *            the value for shop_store_nav.iscate
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setIscate(String iscate) {
		this.iscate = iscate == null ? null : iscate.trim();
	}

	public Long getCateid() {
		return cateid;
	}

	public void setCateid(Long cateid) {
		this.cateid = cateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_store_nav.blank
	 * 
	 * @return the value of shop_store_nav.blank
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public String getBlank() {
		return blank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.blank
	 * 
	 * @param blank
	 *            the value for shop_store_nav.blank
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setBlank(String blank) {
		this.blank = blank == null ? null : blank.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_store_nav.state
	 * 
	 * @return the value of shop_store_nav.state
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.state
	 * 
	 * @param state
	 *            the value for shop_store_nav.state
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_store_nav.siteid
	 * 
	 * @return the value of shop_store_nav.siteid
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public Long getSiteid() {
		return siteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_store_nav.siteid
	 * 
	 * @param siteid
	 *            the value for shop_store_nav.siteid
	 * 
	 * @mbggenerated Wed Jun 24 16:46:49 CST 2015
	 */
	public void setSiteid(Long siteid) {
		this.siteid = siteid;
	}
}