package com.gsccs.b2c.plat.shop.model;

import java.util.ArrayList;
import java.util.List;

import com.gsccs.b2c.plat.bass.BaseExample;

public class StoreCateExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public StoreCateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("site_id is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("site_id is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(Long value) {
            addCriterion("site_id =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(Long value) {
            addCriterion("site_id <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(Long value) {
            addCriterion("site_id >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(Long value) {
            addCriterion("site_id >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(Long value) {
            addCriterion("site_id <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(Long value) {
            addCriterion("site_id <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<Long> values) {
            addCriterion("site_id in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<Long> values) {
            addCriterion("site_id not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(Long value1, Long value2) {
            addCriterion("site_id between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(Long value1, Long value2) {
            addCriterion("site_id not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andCateidsIsNull() {
            addCriterion("cateids is null");
            return (Criteria) this;
        }

        public Criteria andCateidsIsNotNull() {
            addCriterion("cateids is not null");
            return (Criteria) this;
        }

        public Criteria andCateidsEqualTo(String value) {
            addCriterion("cateids =", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsNotEqualTo(String value) {
            addCriterion("cateids <>", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsGreaterThan(String value) {
            addCriterion("cateids >", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsGreaterThanOrEqualTo(String value) {
            addCriterion("cateids >=", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsLessThan(String value) {
            addCriterion("cateids <", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsLessThanOrEqualTo(String value) {
            addCriterion("cateids <=", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsLike(String value) {
            addCriterion("cateids like", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsNotLike(String value) {
            addCriterion("cateids not like", value, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsIn(List<String> values) {
            addCriterion("cateids in", values, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsNotIn(List<String> values) {
            addCriterion("cateids not in", values, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsBetween(String value1, String value2) {
            addCriterion("cateids between", value1, value2, "cateids");
            return (Criteria) this;
        }

        public Criteria andCateidsNotBetween(String value1, String value2) {
            addCriterion("cateids not between", value1, value2, "cateids");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_store_cate
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 13 15:50:25 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}