package com.gsccs.b2c.plat.shop.model;

import java.util.ArrayList;
import java.util.List;

import com.gsccs.b2c.plat.bass.BaseExample;

public class TypeExample extends BaseExample {
	protected String orderByClause;

	protected boolean distinct;

	protected List<Criteria> oredCriteria;

	public TypeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andAliasIsNull() {
			addCriterion("alias is null");
			return (Criteria) this;
		}

		public Criteria andAliasIsNotNull() {
			addCriterion("alias is not null");
			return (Criteria) this;
		}

		public Criteria andAliasEqualTo(String value) {
			addCriterion("alias =", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotEqualTo(String value) {
			addCriterion("alias <>", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThan(String value) {
			addCriterion("alias >", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThanOrEqualTo(String value) {
			addCriterion("alias >=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThan(String value) {
			addCriterion("alias <", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThanOrEqualTo(String value) {
			addCriterion("alias <=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLike(String value) {
			addCriterion("alias like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotLike(String value) {
			addCriterion("alias not like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasIn(List<String> values) {
			addCriterion("alias in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotIn(List<String> values) {
			addCriterion("alias not in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasBetween(String value1, String value2) {
			addCriterion("alias between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotBetween(String value1, String value2) {
			addCriterion("alias not between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalIsNull() {
			addCriterion("is_physical is null");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalIsNotNull() {
			addCriterion("is_physical is not null");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalEqualTo(String value) {
			addCriterion("is_physical =", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalNotEqualTo(String value) {
			addCriterion("is_physical <>", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalGreaterThan(String value) {
			addCriterion("is_physical >", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalGreaterThanOrEqualTo(String value) {
			addCriterion("is_physical >=", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalLessThan(String value) {
			addCriterion("is_physical <", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalLessThanOrEqualTo(String value) {
			addCriterion("is_physical <=", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalLike(String value) {
			addCriterion("is_physical like", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalNotLike(String value) {
			addCriterion("is_physical not like", value, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalIn(List<String> values) {
			addCriterion("is_physical in", values, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalNotIn(List<String> values) {
			addCriterion("is_physical not in", values, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalBetween(String value1, String value2) {
			addCriterion("is_physical between", value1, value2, "isPhysical");
			return (Criteria) this;
		}

		public Criteria andIsPhysicalNotBetween(String value1, String value2) {
			addCriterion("is_physical not between", value1, value2,
					"isPhysical");
			return (Criteria) this;
		}

		public Criteria andUseBrandIsNull() {
			addCriterion("use_brand is null");
			return (Criteria) this;
		}

		public Criteria andUseBrandIsNotNull() {
			addCriterion("use_brand is not null");
			return (Criteria) this;
		}

		public Criteria andUseBrandEqualTo(String value) {
			addCriterion("use_brand =", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandNotEqualTo(String value) {
			addCriterion("use_brand <>", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandGreaterThan(String value) {
			addCriterion("use_brand >", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandGreaterThanOrEqualTo(String value) {
			addCriterion("use_brand >=", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandLessThan(String value) {
			addCriterion("use_brand <", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandLessThanOrEqualTo(String value) {
			addCriterion("use_brand <=", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandLike(String value) {
			addCriterion("use_brand like", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandNotLike(String value) {
			addCriterion("use_brand not like", value, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandIn(List<String> values) {
			addCriterion("use_brand in", values, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandNotIn(List<String> values) {
			addCriterion("use_brand not in", values, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandBetween(String value1, String value2) {
			addCriterion("use_brand between", value1, value2, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUseBrandNotBetween(String value1, String value2) {
			addCriterion("use_brand not between", value1, value2, "useBrand");
			return (Criteria) this;
		}

		public Criteria andUsePropsIsNull() {
			addCriterion("use_props is null");
			return (Criteria) this;
		}

		public Criteria andUsePropsIsNotNull() {
			addCriterion("use_props is not null");
			return (Criteria) this;
		}

		public Criteria andUsePropsEqualTo(String value) {
			addCriterion("use_props =", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsNotEqualTo(String value) {
			addCriterion("use_props <>", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsGreaterThan(String value) {
			addCriterion("use_props >", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsGreaterThanOrEqualTo(String value) {
			addCriterion("use_props >=", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsLessThan(String value) {
			addCriterion("use_props <", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsLessThanOrEqualTo(String value) {
			addCriterion("use_props <=", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsLike(String value) {
			addCriterion("use_props like", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsNotLike(String value) {
			addCriterion("use_props not like", value, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsIn(List<String> values) {
			addCriterion("use_props in", values, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsNotIn(List<String> values) {
			addCriterion("use_props not in", values, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsBetween(String value1, String value2) {
			addCriterion("use_props between", value1, value2, "useProps");
			return (Criteria) this;
		}

		public Criteria andUsePropsNotBetween(String value1, String value2) {
			addCriterion("use_props not between", value1, value2, "useProps");
			return (Criteria) this;
		}

		public Criteria andUseParamsIsNull() {
			addCriterion("use_params is null");
			return (Criteria) this;
		}

		public Criteria andUseParamsIsNotNull() {
			addCriterion("use_params is not null");
			return (Criteria) this;
		}

		public Criteria andUseParamsEqualTo(String value) {
			addCriterion("use_params =", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsNotEqualTo(String value) {
			addCriterion("use_params <>", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsGreaterThan(String value) {
			addCriterion("use_params >", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsGreaterThanOrEqualTo(String value) {
			addCriterion("use_params >=", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsLessThan(String value) {
			addCriterion("use_params <", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsLessThanOrEqualTo(String value) {
			addCriterion("use_params <=", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsLike(String value) {
			addCriterion("use_params like", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsNotLike(String value) {
			addCriterion("use_params not like", value, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsIn(List<String> values) {
			addCriterion("use_params in", values, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsNotIn(List<String> values) {
			addCriterion("use_params not in", values, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsBetween(String value1, String value2) {
			addCriterion("use_params between", value1, value2, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseParamsNotBetween(String value1, String value2) {
			addCriterion("use_params not between", value1, value2, "useParams");
			return (Criteria) this;
		}

		public Criteria andUseMinfoIsNull() {
			addCriterion("use_minfo is null");
			return (Criteria) this;
		}

		public Criteria andUseMinfoIsNotNull() {
			addCriterion("use_minfo is not null");
			return (Criteria) this;
		}

		public Criteria andUseMinfoEqualTo(String value) {
			addCriterion("use_minfo =", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoNotEqualTo(String value) {
			addCriterion("use_minfo <>", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoGreaterThan(String value) {
			addCriterion("use_minfo >", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoGreaterThanOrEqualTo(String value) {
			addCriterion("use_minfo >=", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoLessThan(String value) {
			addCriterion("use_minfo <", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoLessThanOrEqualTo(String value) {
			addCriterion("use_minfo <=", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoLike(String value) {
			addCriterion("use_minfo like", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoNotLike(String value) {
			addCriterion("use_minfo not like", value, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoIn(List<String> values) {
			addCriterion("use_minfo in", values, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoNotIn(List<String> values) {
			addCriterion("use_minfo not in", values, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoBetween(String value1, String value2) {
			addCriterion("use_minfo between", value1, value2, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseMinfoNotBetween(String value1, String value2) {
			addCriterion("use_minfo not between", value1, value2, "useMinfo");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreIsNull() {
			addCriterion("use_floatstore is null");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreIsNotNull() {
			addCriterion("use_floatstore is not null");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreEqualTo(String value) {
			addCriterion("use_floatstore =", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreNotEqualTo(String value) {
			addCriterion("use_floatstore <>", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreGreaterThan(String value) {
			addCriterion("use_floatstore >", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreGreaterThanOrEqualTo(String value) {
			addCriterion("use_floatstore >=", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreLessThan(String value) {
			addCriterion("use_floatstore <", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreLessThanOrEqualTo(String value) {
			addCriterion("use_floatstore <=", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreLike(String value) {
			addCriterion("use_floatstore like", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreNotLike(String value) {
			addCriterion("use_floatstore not like", value, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreIn(List<String> values) {
			addCriterion("use_floatstore in", values, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreNotIn(List<String> values) {
			addCriterion("use_floatstore not in", values, "useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreBetween(String value1, String value2) {
			addCriterion("use_floatstore between", value1, value2,
					"useFloatstore");
			return (Criteria) this;
		}

		public Criteria andUseFloatstoreNotBetween(String value1, String value2) {
			addCriterion("use_floatstore not between", value1, value2,
					"useFloatstore");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("state like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("state not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNull() {
			addCriterion("orderNum is null");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNotNull() {
			addCriterion("orderNum is not null");
			return (Criteria) this;
		}

		public Criteria andOrdernumEqualTo(Integer value) {
			addCriterion("orderNum =", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotEqualTo(Integer value) {
			addCriterion("orderNum <>", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThan(Integer value) {
			addCriterion("orderNum >", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThanOrEqualTo(Integer value) {
			addCriterion("orderNum >=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThan(Integer value) {
			addCriterion("orderNum <", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThanOrEqualTo(Integer value) {
			addCriterion("orderNum <=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumIn(List<Integer> values) {
			addCriterion("orderNum in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotIn(List<Integer> values) {
			addCriterion("orderNum not in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumBetween(Integer value1, Integer value2) {
			addCriterion("orderNum between", value1, value2, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotBetween(Integer value1, Integer value2) {
			addCriterion("orderNum not between", value1, value2, "ordernum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_type
	 * 
	 * @mbggenerated do_not_delete_during_merge Mon Mar 16 15:17:19 CST 2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}