package com.gsccs.b2c.plat.site.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.b2c.plat.site.model.BannerExample;
import com.gsccs.eb.api.domain.site.Banner;

public interface BannerMapper {

	int countByExample(BannerExample example);

	int deleteByExample(BannerExample example);

	int deleteByPrimaryKey(String id);

	int insert(Banner record);

	int insertSelective(Banner record);

	List<Banner> selectByExample(BannerExample example);

	Banner selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table site_storey_banner
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Banner record,
			@Param("example") BannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table site_storey_banner
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	int updateByExample(@Param("record") Banner record,
			@Param("example") BannerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table site_storey_banner
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	int updateByPrimaryKeySelective(Banner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table site_storey_banner
	 * 
	 * @mbggenerated Sun Nov 15 20:24:35 CST 2015
	 */
	int updateByPrimaryKey(Banner record);
}