package com.gsccs.b2c.plat.site.dao;

import com.gsccs.b2c.plat.site.model.DeliverTypeT;
import com.gsccs.b2c.plat.site.model.DeliverTypeTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliverTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int countByExample(DeliverTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int deleteByExample(DeliverTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int insert(DeliverTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int insertSelective(DeliverTypeT record);

   
    List<DeliverTypeT> selectByExample(DeliverTypeTExample example);
    
    List<DeliverTypeT> selectPageByExample(DeliverTypeTExample example);
   
    DeliverTypeT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") DeliverTypeT record, @Param("example") DeliverTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int updateByExample(@Param("record") DeliverTypeT record, @Param("example") DeliverTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int updateByPrimaryKeySelective(DeliverTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_deliver_type
     *
     * @mbggenerated Fri Jun 05 14:47:54 CST 2015
     */
    int updateByPrimaryKey(DeliverTypeT record);
    
    long selectMaxId();
}