package com.gsccs.b2c.plat.site.dao;

import com.gsccs.b2c.plat.site.model.StoreyItem;
import com.gsccs.b2c.plat.site.model.StoreyItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreyItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int countByExample(StoreyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int deleteByExample(StoreyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int insert(StoreyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int insertSelective(StoreyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    List<StoreyItem> selectByExample(StoreyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    StoreyItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") StoreyItem record, @Param("example") StoreyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int updateByExample(@Param("record") StoreyItem record, @Param("example") StoreyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int updateByPrimaryKeySelective(StoreyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_item
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int updateByPrimaryKey(StoreyItem record);
}