package com.gsccs.b2c.plat.site.dao;

import com.gsccs.b2c.plat.site.model.StoreyList;
import com.gsccs.b2c.plat.site.model.StoreyListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreyListMapper {
    
    int countByExample(StoreyListExample example);
    int deleteByExample(StoreyListExample example);
    int deleteByPrimaryKey(String id);
    int insert(StoreyList record);
    List<StoreyList> selectByExample(StoreyListExample example);
    StoreyList selectByPrimaryKey(String id);
    int updateByExample(@Param("record") StoreyList record, @Param("example") StoreyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_list
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int updateByPrimaryKeySelective(StoreyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_list
     *
     * @mbggenerated Sun Nov 15 17:49:02 CST 2015
     */
    int updateByPrimaryKey(StoreyList record);
}