package com.gsccs.b2c.plat.site.dao;

import com.gsccs.b2c.plat.site.model.StoreyBanner;
import com.gsccs.b2c.plat.site.model.StoreyBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreyBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int countByExample(StoreyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int deleteByExample(StoreyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int insert(StoreyBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int insertSelective(StoreyBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    List<StoreyBanner> selectByExample(StoreyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    StoreyBanner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") StoreyBanner record, @Param("example") StoreyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int updateByExample(@Param("record") StoreyBanner record, @Param("example") StoreyBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int updateByPrimaryKeySelective(StoreyBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_storey_banner
     *
     * @mbggenerated Sun Nov 15 20:24:35 CST 2015
     */
    int updateByPrimaryKey(StoreyBanner record);
}