package com.gsccs.b2c.plat.rated.model;


/**
 * 商品评价
 * @author x.d zhang
 *
 */
public class EvalGoodsT {
    
    private Long id;
    private Long productid;
    private Long userid;
    private String account;
    private Long siteid;
    private String content;
    private String addtime;
    private Integer score;

    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.id
     *
     * @param id the value for site_evaldetail_1001.id
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.productid
     *
     * @return the value of site_evaldetail_1001.productid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.productid
     *
     * @param productid the value for site_evaldetail_1001.productid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.userid
     *
     * @return the value of site_evaldetail_1001.userid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.userid
     *
     * @param userid the value for site_evaldetail_1001.userid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.account
     *
     * @return the value of site_evaldetail_1001.account
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.account
     *
     * @param account the value for site_evaldetail_1001.account
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.siteid
     *
     * @return the value of site_evaldetail_1001.siteid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Long getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.siteid
     *
     * @param siteid the value for site_evaldetail_1001.siteid
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.content
     *
     * @return the value of site_evaldetail_1001.content
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.content
     *
     * @param content the value for site_evaldetail_1001.content
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.addtime
     *
     * @return the value of site_evaldetail_1001.addtime
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.addtime
     *
     * @param addtime the value for site_evaldetail_1001.addtime
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_evaldetail_1001.score
     *
     * @return the value of site_evaldetail_1001.score
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_evaldetail_1001.score
     *
     * @param score the value for site_evaldetail_1001.score
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}