package com.gsccs.eb.api.domain.goods;


/**
 * 属性  
 * @author x.d zhang
 *
 */
public class Property {

	private Long id;
	private String title;
	private String alias;
	private String showType;
	private String options;
	private Long typeId;
	private String state;
	private Integer ordernum;

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_props.id
	 * 
	 * @param id
	 *            the value for shop_props.id
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_props.title
	 * 
	 * @return the value of shop_props.title
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_props.title
	 * 
	 * @param title
	 *            the value for shop_props.title
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias == null ? null : alias.trim();
	}

	
	public String getShowType() {
		return showType;
	}

	
	public void setShowType(String showType) {
		this.showType = showType == null ? null : showType.trim();
	}

	public String getOptions() {
		return options;
	}

	public void setOptions(String options) {
		this.options = options == null ? null : options.trim();
	}

	public Long getTypeId() {
		return typeId;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	public Integer getOrdernum() {
		return ordernum;
	}

	public void setOrdernum(Integer ordernum) {
		this.ordernum = ordernum;
	}
}