package com.gsccs.eb.api.domain.goods;

import java.util.List;

import com.gsccs.b2c.api.domain.Domain;

/**
 * 规格
 * @author x.d zhang
 *
 */
public class Specific extends Domain{
	
    private Long id;
    private String title;
    private String memo;
    private String alias;
    private String showType;
    private String showModel;
    private String state;
    private Integer ordernum;
    //规格值列表
    private List<SpecVal> specVal;
    
    
    public List<SpecVal> getSpecVal() {
		return specVal;
	}


	public void setSpecVal(List<SpecVal> specVal) {
		this.specVal = specVal;
	}


	public Long getId() {
        return id;
    }

    
    public void setId(Long id) {
        this.id = id;
    }

    
    public String getTitle() {
        return title;
    }

    
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_spec.memo
     *
     * @param memo the value for shop_spec.memo
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_spec.alias
     *
     * @return the value of shop_spec.alias
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_spec.alias
     *
     * @param alias the value for shop_spec.alias
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_spec.show_type
     *
     * @return the value of shop_spec.show_type
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public String getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_spec.show_type
     *
     * @param showType the value for shop_spec.show_type
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public void setShowType(String showType) {
        this.showType = showType == null ? null : showType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_spec.show_model
     *
     * @return the value of shop_spec.show_model
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public String getShowModel() {
        return showModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_spec.show_model
     *
     * @param showModel the value for shop_spec.show_model
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public void setShowModel(String showModel) {
        this.showModel = showModel == null ? null : showModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_spec.state
     *
     * @return the value of shop_spec.state
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    public String getState() {
        return state;
    }

    
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    
    public Integer getOrdernum() {
        return ordernum;
    }

    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }
    
    
}