package com.gsccs.b2c.plat.buyer.model;

import java.math.BigDecimal;

public class Discount {

	private Long id;

	private Long siteId;

	private Long productId;

	private Long goodsId;

	private Long levelId;

	private Float disCount;
	private BigDecimal price;

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.id
	 * 
	 * @param id
	 *            the value for shop_buyer_dis.id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_buyer_dis.site_id
	 * 
	 * @return the value of shop_buyer_dis.site_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public Long getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.site_id
	 * 
	 * @param siteId
	 *            the value for shop_buyer_dis.site_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setSiteId(Long siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_buyer_dis.product_id
	 * 
	 * @return the value of shop_buyer_dis.product_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.product_id
	 * 
	 * @param productId
	 *            the value for shop_buyer_dis.product_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_buyer_dis.goods_id
	 * 
	 * @return the value of shop_buyer_dis.goods_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public Long getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.goods_id
	 * 
	 * @param goodsId
	 *            the value for shop_buyer_dis.goods_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setGoodsId(Long goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_buyer_dis.level_id
	 * 
	 * @return the value of shop_buyer_dis.level_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public Long getLevelId() {
		return levelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.level_id
	 * 
	 * @param levelId
	 *            the value for shop_buyer_dis.level_id
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setLevelId(Long levelId) {
		this.levelId = levelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_buyer_dis.dis_count
	 * 
	 * @return the value of shop_buyer_dis.dis_count
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public Float getDisCount() {
		return disCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.dis_count
	 * 
	 * @param disCount
	 *            the value for shop_buyer_dis.dis_count
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setDisCount(Float disCount) {
		this.disCount = disCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shop_buyer_dis.price
	 * 
	 * @return the value of shop_buyer_dis.price
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shop_buyer_dis.price
	 * 
	 * @param price
	 *            the value for shop_buyer_dis.price
	 * 
	 * @mbggenerated Wed Apr 15 11:30:27 CST 2015
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
}