package com.gsccs.b2c.plat.order.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import com.gsccs.b2c.plat.bass.BaseExample;

public class OrderItemExample extends BaseExample {

	protected String orderByClause;
	protected boolean distinct;
	protected List<Criteria> oredCriteria;

	public OrderItemExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNull() {
			addCriterion("orderid is null");
			return (Criteria) this;
		}

		public Criteria andOrderidIsNotNull() {
			addCriterion("orderid is not null");
			return (Criteria) this;
		}

		public Criteria andOrderidEqualTo(Long value) {
			addCriterion("orderid =", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotEqualTo(Long value) {
			addCriterion("orderid <>", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThan(Long value) {
			addCriterion("orderid >", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidGreaterThanOrEqualTo(Long value) {
			addCriterion("orderid >=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThan(Long value) {
			addCriterion("orderid <", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidLessThanOrEqualTo(Long value) {
			addCriterion("orderid <=", value, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidIn(List<Long> values) {
			addCriterion("orderid in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotIn(List<Long> values) {
			addCriterion("orderid not in", values, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidBetween(Long value1, Long value2) {
			addCriterion("orderid between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andOrderidNotBetween(Long value1, Long value2) {
			addCriterion("orderid not between", value1, value2, "orderid");
			return (Criteria) this;
		}

		public Criteria andProductidIsNull() {
			addCriterion("productid is null");
			return (Criteria) this;
		}

		public Criteria andProductidIsNotNull() {
			addCriterion("productid is not null");
			return (Criteria) this;
		}

		public Criteria andProductidEqualTo(Long value) {
			addCriterion("productid =", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotEqualTo(Long value) {
			addCriterion("productid <>", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidGreaterThan(Long value) {
			addCriterion("productid >", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidGreaterThanOrEqualTo(Long value) {
			addCriterion("productid >=", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLessThan(Long value) {
			addCriterion("productid <", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLessThanOrEqualTo(Long value) {
			addCriterion("productid <=", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidIn(List<Long> values) {
			addCriterion("productid in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotIn(List<Long> values) {
			addCriterion("productid not in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidBetween(Long value1, Long value2) {
			addCriterion("productid between", value1, value2, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotBetween(Long value1, Long value2) {
			addCriterion("productid not between", value1, value2, "productid");
			return (Criteria) this;
		}

		public Criteria andSkuidIsNull() {
			addCriterion("skuid is null");
			return (Criteria) this;
		}

		public Criteria andSkuidIsNotNull() {
			addCriterion("skuid is not null");
			return (Criteria) this;
		}

		public Criteria andSkuidEqualTo(Long value) {
			addCriterion("skuid =", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidNotEqualTo(Long value) {
			addCriterion("skuid <>", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidGreaterThan(Long value) {
			addCriterion("skuid >", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidGreaterThanOrEqualTo(Long value) {
			addCriterion("skuid >=", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidLessThan(Long value) {
			addCriterion("skuid <", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidLessThanOrEqualTo(Long value) {
			addCriterion("skuid <=", value, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidIn(List<Long> values) {
			addCriterion("skuid in", values, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidNotIn(List<Long> values) {
			addCriterion("skuid not in", values, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidBetween(Long value1, Long value2) {
			addCriterion("skuid between", value1, value2, "skuid");
			return (Criteria) this;
		}

		public Criteria andSkuidNotBetween(Long value1, Long value2) {
			addCriterion("skuid not between", value1, value2, "skuid");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<Integer> values) {
			addCriterion("num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<Integer> values) {
			addCriterion("num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("num not between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(BigDecimal value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(BigDecimal value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(BigDecimal value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(BigDecimal value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<BigDecimal> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<BigDecimal> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andAccoutIsNull() {
			addCriterion("accout is null");
			return (Criteria) this;
		}

		public Criteria andAccoutIsNotNull() {
			addCriterion("accout is not null");
			return (Criteria) this;
		}

		public Criteria andAccoutEqualTo(String value) {
			addCriterion("accout =", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutNotEqualTo(String value) {
			addCriterion("accout <>", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutGreaterThan(String value) {
			addCriterion("accout >", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutGreaterThanOrEqualTo(String value) {
			addCriterion("accout >=", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutLessThan(String value) {
			addCriterion("accout <", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutLessThanOrEqualTo(String value) {
			addCriterion("accout <=", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutLike(String value) {
			addCriterion("accout like", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutNotLike(String value) {
			addCriterion("accout not like", value, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutIn(List<String> values) {
			addCriterion("accout in", values, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutNotIn(List<String> values) {
			addCriterion("accout not in", values, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutBetween(String value1, String value2) {
			addCriterion("accout between", value1, value2, "accout");
			return (Criteria) this;
		}

		public Criteria andAccoutNotBetween(String value1, String value2) {
			addCriterion("accout not between", value1, value2, "accout");
			return (Criteria) this;
		}

		public Criteria andBuyerIsNull() {
			addCriterion("buyer is null");
			return (Criteria) this;
		}

		public Criteria andBuyerIsNotNull() {
			addCriterion("buyer is not null");
			return (Criteria) this;
		}

		public Criteria andBuyerEqualTo(String value) {
			addCriterion("buyer =", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotEqualTo(String value) {
			addCriterion("buyer <>", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerGreaterThan(String value) {
			addCriterion("buyer >", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerGreaterThanOrEqualTo(String value) {
			addCriterion("buyer >=", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerLessThan(String value) {
			addCriterion("buyer <", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerLessThanOrEqualTo(String value) {
			addCriterion("buyer <=", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerLike(String value) {
			addCriterion("buyer like", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotLike(String value) {
			addCriterion("buyer not like", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerIn(List<String> values) {
			addCriterion("buyer in", values, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotIn(List<String> values) {
			addCriterion("buyer not in", values, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerBetween(String value1, String value2) {
			addCriterion("buyer between", value1, value2, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotBetween(String value1, String value2) {
			addCriterion("buyer not between", value1, value2, "buyer");
			return (Criteria) this;
		}

		public Criteria andSellerIsNull() {
			addCriterion("seller is null");
			return (Criteria) this;
		}

		public Criteria andSellerIsNotNull() {
			addCriterion("seller is not null");
			return (Criteria) this;
		}

		public Criteria andSellerEqualTo(String value) {
			addCriterion("seller =", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotEqualTo(String value) {
			addCriterion("seller <>", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerGreaterThan(String value) {
			addCriterion("seller >", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerGreaterThanOrEqualTo(String value) {
			addCriterion("seller >=", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerLessThan(String value) {
			addCriterion("seller <", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerLessThanOrEqualTo(String value) {
			addCriterion("seller <=", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerLike(String value) {
			addCriterion("seller like", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotLike(String value) {
			addCriterion("seller not like", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerIn(List<String> values) {
			addCriterion("seller in", values, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotIn(List<String> values) {
			addCriterion("seller not in", values, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerBetween(String value1, String value2) {
			addCriterion("seller between", value1, value2, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotBetween(String value1, String value2) {
			addCriterion("seller not between", value1, value2, "seller");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(String value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(String value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(String value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(String value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(String value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(String value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLike(String value) {
			addCriterion("addtime like", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotLike(String value) {
			addCriterion("addtime not like", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<String> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<String> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(String value1, String value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(String value1, String value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("state like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("state not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_item
	 * 
	 * @mbggenerated do_not_delete_during_merge Fri Jun 19 10:30:34 CST 2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_item
	 * 
	 * @mbggenerated Fri Jun 19 10:30:34 CST 2015
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}