package com.gsccs.b2c.plat.order.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.gsccs.b2c.plat.bass.BaseExample;

public class OrderExample extends BaseExample {

	protected String orderByClause;
	protected boolean distinct;
	protected List<Criteria> oredCriteria;

	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andSerialnumIsNull() {
			addCriterion("serialnum is null");
			return (Criteria) this;
		}

		public Criteria andSerialnumIsNotNull() {
			addCriterion("serialnum is not null");
			return (Criteria) this;
		}

		public Criteria andSerialnumEqualTo(String value) {
			addCriterion("serialnum =", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumNotEqualTo(String value) {
			addCriterion("serialnum <>", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumGreaterThan(String value) {
			addCriterion("serialnum >", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumGreaterThanOrEqualTo(String value) {
			addCriterion("serialnum >=", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumLessThan(String value) {
			addCriterion("serialnum <", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumLessThanOrEqualTo(String value) {
			addCriterion("serialnum <=", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumLike(String value) {
			addCriterion("serialnum like", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumNotLike(String value) {
			addCriterion("serialnum not like", value, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumIn(List<String> values) {
			addCriterion("serialnum in", values, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumNotIn(List<String> values) {
			addCriterion("serialnum not in", values, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumBetween(String value1, String value2) {
			addCriterion("serialnum between", value1, value2, "serialnum");
			return (Criteria) this;
		}

		public Criteria andSerialnumNotBetween(String value1, String value2) {
			addCriterion("serialnum not between", value1, value2, "serialnum");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andBuyeridIsNull() {
			addCriterion("buyerid is null");
			return (Criteria) this;
		}

		public Criteria andBuyeridIsNotNull() {
			addCriterion("buyerid is not null");
			return (Criteria) this;
		}

		public Criteria andBuyeridEqualTo(Long value) {
			addCriterion("buyerid =", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotEqualTo(Long value) {
			addCriterion("buyerid <>", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridGreaterThan(Long value) {
			addCriterion("buyerid >", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridGreaterThanOrEqualTo(Long value) {
			addCriterion("buyerid >=", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridLessThan(Long value) {
			addCriterion("buyerid <", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridLessThanOrEqualTo(Long value) {
			addCriterion("buyerid <=", value, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridIn(List<Long> values) {
			addCriterion("buyerid in", values, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotIn(List<Long> values) {
			addCriterion("buyerid not in", values, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridBetween(Long value1, Long value2) {
			addCriterion("buyerid between", value1, value2, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyeridNotBetween(Long value1, Long value2) {
			addCriterion("buyerid not between", value1, value2, "buyerid");
			return (Criteria) this;
		}

		public Criteria andBuyernickIsNull() {
			addCriterion("buyernick is null");
			return (Criteria) this;
		}

		public Criteria andBuyernickIsNotNull() {
			addCriterion("buyernick is not null");
			return (Criteria) this;
		}

		public Criteria andBuyernickEqualTo(String value) {
			addCriterion("buyernick =", value, "buyernick");
			return (Criteria) this;
		}

		public Criteria andBuyernickNotEqualTo(String value) {
			addCriterion("buyernick <>", value, "buyernick");
			return (Criteria) this;
		}

		public Criteria andBuyernickLike(String value) {
			addCriterion("buyernick like", value, "buyernick");
			return (Criteria) this;
		}

		public Criteria andBuyernickNotLike(String value) {
			addCriterion("buyernick not like", value, "buyernick");
			return (Criteria) this;
		}

		public Criteria andBuyernickIn(List<String> values) {
			addCriterion("buyernick in", values, "buyernick");
			return (Criteria) this;
		}

		public Criteria andBuyernickNotIn(List<String> values) {
			addCriterion("buyernick not in", values, "buyernick");
			return (Criteria) this;
		}

		public Criteria andShopidIsNull() {
			addCriterion("shopid is null");
			return (Criteria) this;
		}

		public Criteria andShopidIsNotNull() {
			addCriterion("shopid is not null");
			return (Criteria) this;
		}

		public Criteria andShopidEqualTo(Long value) {
			addCriterion("shopid =", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andShopidNotEqualTo(Long value) {
			addCriterion("shopid <>", value, "storeid");
			return (Criteria) this;
		}

		public Criteria andShopidIn(List<Long> values) {
			addCriterion("shopid in", values, "storeid");
			return (Criteria) this;
		}

		public Criteria andShopidNotIn(List<Long> values) {
			addCriterion("shopid not in", values, "storeid");
			return (Criteria) this;
		}

		public Criteria andShopidBetween(Long value1, Long value2) {
			addCriterion("shopid between", value1, value2, "storeid");
			return (Criteria) this;
		}

		public Criteria andShopidNotBetween(Long value1, Long value2) {
			addCriterion("shopid not between", value1, value2, "storeid");
			return (Criteria) this;
		}

		public Criteria andShopnameIsNull() {
			addCriterion("shopname is null");
			return (Criteria) this;
		}

		public Criteria andShopnameIsNotNull() {
			addCriterion("shopname is not null");
			return (Criteria) this;
		}

		public Criteria andShopnameEqualTo(String value) {
			addCriterion("shopname =", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameNotEqualTo(String value) {
			addCriterion("shopname <>", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameLike(String value) {
			addCriterion("shopname like", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andShopnameNotLike(String value) {
			addCriterion("shopname not like", value, "shopname");
			return (Criteria) this;
		}

		public Criteria andPaytypeIsNull() {
			addCriterion("paytype is null");
			return (Criteria) this;
		}

		public Criteria andPaytypeIsNotNull() {
			addCriterion("paytype is not null");
			return (Criteria) this;
		}

		public Criteria andPaytypeEqualTo(String value) {
			addCriterion("paytype =", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeNotEqualTo(String value) {
			addCriterion("paytype <>", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeGreaterThan(String value) {
			addCriterion("paytype >", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
			addCriterion("paytype >=", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeLessThan(String value) {
			addCriterion("paytype <", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeLessThanOrEqualTo(String value) {
			addCriterion("paytype <=", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeLike(String value) {
			addCriterion("paytype like", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeNotLike(String value) {
			addCriterion("paytype not like", value, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeIn(List<String> values) {
			addCriterion("paytype in", values, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeNotIn(List<String> values) {
			addCriterion("paytype not in", values, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeBetween(String value1, String value2) {
			addCriterion("paytype between", value1, value2, "paytype");
			return (Criteria) this;
		}

		public Criteria andPaytypeNotBetween(String value1, String value2) {
			addCriterion("paytype not between", value1, value2, "paytype");
			return (Criteria) this;
		}

		public Criteria andTelnumIsNull() {
			addCriterion("telnum is null");
			return (Criteria) this;
		}

		public Criteria andTelnumIsNotNull() {
			addCriterion("telnum is not null");
			return (Criteria) this;
		}

		public Criteria andTelnumEqualTo(String value) {
			addCriterion("telnum =", value, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumIn(List<String> values) {
			addCriterion("telnum in", values, "telnum");
			return (Criteria) this;
		}

		public Criteria andTelnumNotIn(List<String> values) {
			addCriterion("telnum not in", values, "telnum");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andShiptypeIsNull() {
			addCriterion("shiptype is null");
			return (Criteria) this;
		}

		public Criteria andShiptypeIsNotNull() {
			addCriterion("shiptype is not null");
			return (Criteria) this;
		}

		public Criteria andShiptypeEqualTo(String value) {
			addCriterion("shiptype =", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeNotEqualTo(String value) {
			addCriterion("shiptype <>", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeGreaterThan(String value) {
			addCriterion("shiptype >", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeGreaterThanOrEqualTo(String value) {
			addCriterion("shiptype >=", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeLessThan(String value) {
			addCriterion("shiptype <", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeLessThanOrEqualTo(String value) {
			addCriterion("shiptype <=", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeLike(String value) {
			addCriterion("shiptype like", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeNotLike(String value) {
			addCriterion("shiptype not like", value, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeIn(List<String> values) {
			addCriterion("shiptype in", values, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeNotIn(List<String> values) {
			addCriterion("shiptype not in", values, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeBetween(String value1, String value2) {
			addCriterion("shiptype between", value1, value2, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShiptypeNotBetween(String value1, String value2) {
			addCriterion("shiptype not between", value1, value2, "shiptype");
			return (Criteria) this;
		}

		public Criteria andShipfeeIsNull() {
			addCriterion("shipfee is null");
			return (Criteria) this;
		}

		public Criteria andShipfeeIsNotNull() {
			addCriterion("shipfee is not null");
			return (Criteria) this;
		}

		public Criteria andShipfeeEqualTo(BigDecimal value) {
			addCriterion("shipfee =", value, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeNotEqualTo(BigDecimal value) {
			addCriterion("shipfee <>", value, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeGreaterThan(BigDecimal value) {
			addCriterion("shipfee >", value, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("shipfee >=", value, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeLessThan(BigDecimal value) {
			addCriterion("shipfee <", value, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("shipfee <=", value, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeIn(List<BigDecimal> values) {
			addCriterion("shipfee in", values, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeNotIn(List<BigDecimal> values) {
			addCriterion("shipfee not in", values, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("shipfee between", value1, value2, "shipfee");
			return (Criteria) this;
		}

		public Criteria andShipfeeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("shipfee not between", value1, value2, "shipfee");
			return (Criteria) this;
		}

		public Criteria andConsigneeIsNull() {
			addCriterion("consignee is null");
			return (Criteria) this;
		}

		public Criteria andConsigneeIsNotNull() {
			addCriterion("consignee is not null");
			return (Criteria) this;
		}

		public Criteria andConsigneeEqualTo(String value) {
			addCriterion("consignee =", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeNotEqualTo(String value) {
			addCriterion("consignee <>", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeGreaterThan(String value) {
			addCriterion("consignee >", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeGreaterThanOrEqualTo(String value) {
			addCriterion("consignee >=", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeLessThan(String value) {
			addCriterion("consignee <", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeLessThanOrEqualTo(String value) {
			addCriterion("consignee <=", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeLike(String value) {
			addCriterion("consignee like", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeNotLike(String value) {
			addCriterion("consignee not like", value, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeIn(List<String> values) {
			addCriterion("consignee in", values, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeNotIn(List<String> values) {
			addCriterion("consignee not in", values, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeBetween(String value1, String value2) {
			addCriterion("consignee between", value1, value2, "consignee");
			return (Criteria) this;
		}

		public Criteria andConsigneeNotBetween(String value1, String value2) {
			addCriterion("consignee not between", value1, value2, "consignee");
			return (Criteria) this;
		}

		public Criteria andReceaddressIsNull() {
			addCriterion("receaddress is null");
			return (Criteria) this;
		}

		public Criteria andReceaddressIsNotNull() {
			addCriterion("receaddress is not null");
			return (Criteria) this;
		}

		public Criteria andReceaddressEqualTo(String value) {
			addCriterion("receaddress =", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressNotEqualTo(String value) {
			addCriterion("receaddress <>", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressGreaterThan(String value) {
			addCriterion("receaddress >", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressGreaterThanOrEqualTo(String value) {
			addCriterion("receaddress >=", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressLessThan(String value) {
			addCriterion("receaddress <", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressLessThanOrEqualTo(String value) {
			addCriterion("receaddress <=", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressLike(String value) {
			addCriterion("receaddress like", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressNotLike(String value) {
			addCriterion("receaddress not like", value, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressIn(List<String> values) {
			addCriterion("receaddress in", values, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressNotIn(List<String> values) {
			addCriterion("receaddress not in", values, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressBetween(String value1, String value2) {
			addCriterion("receaddress between", value1, value2, "receaddress");
			return (Criteria) this;
		}

		public Criteria andReceaddressNotBetween(String value1, String value2) {
			addCriterion("receaddress not between", value1, value2,
					"receaddress");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNull() {
			addCriterion("ordertype is null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIsNotNull() {
			addCriterion("ordertype is not null");
			return (Criteria) this;
		}

		public Criteria andOrdertypeEqualTo(String value) {
			addCriterion("ordertype =", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotEqualTo(String value) {
			addCriterion("ordertype <>", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThan(String value) {
			addCriterion("ordertype >", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeGreaterThanOrEqualTo(String value) {
			addCriterion("ordertype >=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThan(String value) {
			addCriterion("ordertype <", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLessThanOrEqualTo(String value) {
			addCriterion("ordertype <=", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeLike(String value) {
			addCriterion("ordertype like", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotLike(String value) {
			addCriterion("ordertype not like", value, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeIn(List<String> values) {
			addCriterion("ordertype in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotIn(List<String> values) {
			addCriterion("ordertype not in", values, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeBetween(String value1, String value2) {
			addCriterion("ordertype between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andOrdertypeNotBetween(String value1, String value2) {
			addCriterion("ordertype not between", value1, value2, "ordertype");
			return (Criteria) this;
		}

		public Criteria andIsdelayIsNull() {
			addCriterion("isdelay is null");
			return (Criteria) this;
		}

		public Criteria andIsdelayIsNotNull() {
			addCriterion("isdelay is not null");
			return (Criteria) this;
		}

		public Criteria andIsdelayEqualTo(String value) {
			addCriterion("isdelay =", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayNotEqualTo(String value) {
			addCriterion("isdelay <>", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayGreaterThan(String value) {
			addCriterion("isdelay >", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayGreaterThanOrEqualTo(String value) {
			addCriterion("isdelay >=", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayLessThan(String value) {
			addCriterion("isdelay <", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayLessThanOrEqualTo(String value) {
			addCriterion("isdelay <=", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayLike(String value) {
			addCriterion("isdelay like", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayNotLike(String value) {
			addCriterion("isdelay not like", value, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayIn(List<String> values) {
			addCriterion("isdelay in", values, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayNotIn(List<String> values) {
			addCriterion("isdelay not in", values, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayBetween(String value1, String value2) {
			addCriterion("isdelay between", value1, value2, "isdelay");
			return (Criteria) this;
		}

		public Criteria andIsdelayNotBetween(String value1, String value2) {
			addCriterion("isdelay not between", value1, value2, "isdelay");
			return (Criteria) this;
		}

		public Criteria andTotalfeeIsNull() {
			addCriterion("totalfee is null");
			return (Criteria) this;
		}

		public Criteria andTotalfeeIsNotNull() {
			addCriterion("totalfee is not null");
			return (Criteria) this;
		}

		public Criteria andTotalfeeEqualTo(BigDecimal value) {
			addCriterion("totalfee =", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeNotEqualTo(BigDecimal value) {
			addCriterion("totalfee <>", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeGreaterThan(BigDecimal value) {
			addCriterion("totalfee >", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("totalfee >=", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeLessThan(BigDecimal value) {
			addCriterion("totalfee <", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("totalfee <=", value, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeIn(List<BigDecimal> values) {
			addCriterion("totalfee in", values, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeNotIn(List<BigDecimal> values) {
			addCriterion("totalfee not in", values, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("totalfee between", value1, value2, "totalfee");
			return (Criteria) this;
		}

		public Criteria andTotalfeeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("totalfee not between", value1, value2, "totalfee");
			return (Criteria) this;
		}

		public Criteria andIsdistribIsNull() {
			addCriterion("isdistrib is null");
			return (Criteria) this;
		}

		public Criteria andIsdistribIsNotNull() {
			addCriterion("isdistrib is not null");
			return (Criteria) this;
		}

		public Criteria andIsdistribEqualTo(String value) {
			addCriterion("isdistrib =", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribNotEqualTo(String value) {
			addCriterion("isdistrib <>", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribGreaterThan(String value) {
			addCriterion("isdistrib >", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribGreaterThanOrEqualTo(String value) {
			addCriterion("isdistrib >=", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribLessThan(String value) {
			addCriterion("isdistrib <", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribLessThanOrEqualTo(String value) {
			addCriterion("isdistrib <=", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribLike(String value) {
			addCriterion("isdistrib like", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribNotLike(String value) {
			addCriterion("isdistrib not like", value, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribIn(List<String> values) {
			addCriterion("isdistrib in", values, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribNotIn(List<String> values) {
			addCriterion("isdistrib not in", values, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribBetween(String value1, String value2) {
			addCriterion("isdistrib between", value1, value2, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andIsdistribNotBetween(String value1, String value2) {
			addCriterion("isdistrib not between", value1, value2, "isdistrib");
			return (Criteria) this;
		}

		public Criteria andDistribfeeIsNull() {
			addCriterion("distribfee is null");
			return (Criteria) this;
		}

		public Criteria andDistribfeeIsNotNull() {
			addCriterion("distribfee is not null");
			return (Criteria) this;
		}

		public Criteria andDistribfeeEqualTo(BigDecimal value) {
			addCriterion("distribfee =", value, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeNotEqualTo(BigDecimal value) {
			addCriterion("distribfee <>", value, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeGreaterThan(BigDecimal value) {
			addCriterion("distribfee >", value, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("distribfee >=", value, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeLessThan(BigDecimal value) {
			addCriterion("distribfee <", value, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("distribfee <=", value, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeIn(List<BigDecimal> values) {
			addCriterion("distribfee in", values, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeNotIn(List<BigDecimal> values) {
			addCriterion("distribfee not in", values, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("distribfee between", value1, value2, "distribfee");
			return (Criteria) this;
		}

		public Criteria andDistribfeeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("distribfee not between", value1, value2, "distribfee");
			return (Criteria) this;
		}

		public Criteria andIsbillingIsNull() {
			addCriterion("isbilling is null");
			return (Criteria) this;
		}

		public Criteria andIsbillingIsNotNull() {
			addCriterion("isbilling is not null");
			return (Criteria) this;
		}

		public Criteria andIsbillingEqualTo(String value) {
			addCriterion("isbilling =", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingNotEqualTo(String value) {
			addCriterion("isbilling <>", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingGreaterThan(String value) {
			addCriterion("isbilling >", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingGreaterThanOrEqualTo(String value) {
			addCriterion("isbilling >=", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingLessThan(String value) {
			addCriterion("isbilling <", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingLessThanOrEqualTo(String value) {
			addCriterion("isbilling <=", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingLike(String value) {
			addCriterion("isbilling like", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingNotLike(String value) {
			addCriterion("isbilling not like", value, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingIn(List<String> values) {
			addCriterion("isbilling in", values, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingNotIn(List<String> values) {
			addCriterion("isbilling not in", values, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingBetween(String value1, String value2) {
			addCriterion("isbilling between", value1, value2, "isbilling");
			return (Criteria) this;
		}

		public Criteria andIsbillingNotBetween(String value1, String value2) {
			addCriterion("isbilling not between", value1, value2, "isbilling");
			return (Criteria) this;
		}

		public Criteria andGainscoreIsNull() {
			addCriterion("gainscore is null");
			return (Criteria) this;
		}

		public Criteria andGainscoreIsNotNull() {
			addCriterion("gainscore is not null");
			return (Criteria) this;
		}

		public Criteria andGainscoreEqualTo(Integer value) {
			addCriterion("gainscore =", value, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreNotEqualTo(Integer value) {
			addCriterion("gainscore <>", value, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreGreaterThan(Integer value) {
			addCriterion("gainscore >", value, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("gainscore >=", value, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreLessThan(Integer value) {
			addCriterion("gainscore <", value, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreLessThanOrEqualTo(Integer value) {
			addCriterion("gainscore <=", value, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreIn(List<Integer> values) {
			addCriterion("gainscore in", values, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreNotIn(List<Integer> values) {
			addCriterion("gainscore not in", values, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreBetween(Integer value1, Integer value2) {
			addCriterion("gainscore between", value1, value2, "gainscore");
			return (Criteria) this;
		}

		public Criteria andGainscoreNotBetween(Integer value1, Integer value2) {
			addCriterion("gainscore not between", value1, value2, "gainscore");
			return (Criteria) this;
		}

		public Criteria andCouponidIsNull() {
			addCriterion("couponid is null");
			return (Criteria) this;
		}

		public Criteria andCouponidIsNotNull() {
			addCriterion("couponid is not null");
			return (Criteria) this;
		}

		public Criteria andCouponidEqualTo(Long value) {
			addCriterion("couponid =", value, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidNotEqualTo(Long value) {
			addCriterion("couponid <>", value, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidGreaterThan(Long value) {
			addCriterion("couponid >", value, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidGreaterThanOrEqualTo(Long value) {
			addCriterion("couponid >=", value, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidLessThan(Long value) {
			addCriterion("couponid <", value, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidLessThanOrEqualTo(Long value) {
			addCriterion("couponid <=", value, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidIn(List<Long> values) {
			addCriterion("couponid in", values, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidNotIn(List<Long> values) {
			addCriterion("couponid not in", values, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidBetween(Long value1, Long value2) {
			addCriterion("couponid between", value1, value2, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponidNotBetween(Long value1, Long value2) {
			addCriterion("couponid not between", value1, value2, "couponid");
			return (Criteria) this;
		}

		public Criteria andCouponfeeIsNull() {
			addCriterion("couponfee is null");
			return (Criteria) this;
		}

		public Criteria andCouponfeeIsNotNull() {
			addCriterion("couponfee is not null");
			return (Criteria) this;
		}

		public Criteria andCouponfeeEqualTo(BigDecimal value) {
			addCriterion("couponfee =", value, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeNotEqualTo(BigDecimal value) {
			addCriterion("couponfee <>", value, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeGreaterThan(BigDecimal value) {
			addCriterion("couponfee >", value, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("couponfee >=", value, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeLessThan(BigDecimal value) {
			addCriterion("couponfee <", value, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("couponfee <=", value, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeIn(List<BigDecimal> values) {
			addCriterion("couponfee in", values, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeNotIn(List<BigDecimal> values) {
			addCriterion("couponfee not in", values, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("couponfee between", value1, value2, "couponfee");
			return (Criteria) this;
		}

		public Criteria andCouponfeeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("couponfee not between", value1, value2, "couponfee");
			return (Criteria) this;
		}

		public Criteria andActivityidIsNull() {
			addCriterion("activityid is null");
			return (Criteria) this;
		}

		public Criteria andActivityidIsNotNull() {
			addCriterion("activityid is not null");
			return (Criteria) this;
		}

		public Criteria andActivityidEqualTo(Long value) {
			addCriterion("activityid =", value, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidNotEqualTo(Long value) {
			addCriterion("activityid <>", value, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidGreaterThan(Long value) {
			addCriterion("activityid >", value, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidGreaterThanOrEqualTo(Long value) {
			addCriterion("activityid >=", value, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidLessThan(Long value) {
			addCriterion("activityid <", value, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidLessThanOrEqualTo(Long value) {
			addCriterion("activityid <=", value, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidIn(List<Long> values) {
			addCriterion("activityid in", values, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidNotIn(List<Long> values) {
			addCriterion("activityid not in", values, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidBetween(Long value1, Long value2) {
			addCriterion("activityid between", value1, value2, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityidNotBetween(Long value1, Long value2) {
			addCriterion("activityid not between", value1, value2, "activityid");
			return (Criteria) this;
		}

		public Criteria andActivityfeeIsNull() {
			addCriterion("activityfee is null");
			return (Criteria) this;
		}

		public Criteria andActivityfeeIsNotNull() {
			addCriterion("activityfee is not null");
			return (Criteria) this;
		}

		public Criteria andActivityfeeEqualTo(BigDecimal value) {
			addCriterion("activityfee =", value, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeNotEqualTo(BigDecimal value) {
			addCriterion("activityfee <>", value, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeGreaterThan(BigDecimal value) {
			addCriterion("activityfee >", value, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("activityfee >=", value, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeLessThan(BigDecimal value) {
			addCriterion("activityfee <", value, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("activityfee <=", value, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeIn(List<BigDecimal> values) {
			addCriterion("activityfee in", values, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeNotIn(List<BigDecimal> values) {
			addCriterion("activityfee not in", values, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("activityfee between", value1, value2, "activityfee");
			return (Criteria) this;
		}

		public Criteria andActivityfeeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("activityfee not between", value1, value2,
					"activityfee");
			return (Criteria) this;
		}

		public Criteria andTotalnumIsNull() {
			addCriterion("totalnum is null");
			return (Criteria) this;
		}

		public Criteria andTotalnumIsNotNull() {
			addCriterion("totalnum is not null");
			return (Criteria) this;
		}

		public Criteria andTotalnumEqualTo(Integer value) {
			addCriterion("totalnum =", value, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumNotEqualTo(Integer value) {
			addCriterion("totalnum <>", value, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumGreaterThan(Integer value) {
			addCriterion("totalnum >", value, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumGreaterThanOrEqualTo(Integer value) {
			addCriterion("totalnum >=", value, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumLessThan(Integer value) {
			addCriterion("totalnum <", value, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumLessThanOrEqualTo(Integer value) {
			addCriterion("totalnum <=", value, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumIn(List<Integer> values) {
			addCriterion("totalnum in", values, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumNotIn(List<Integer> values) {
			addCriterion("totalnum not in", values, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumBetween(Integer value1, Integer value2) {
			addCriterion("totalnum between", value1, value2, "totalnum");
			return (Criteria) this;
		}

		public Criteria andTotalnumNotBetween(Integer value1, Integer value2) {
			addCriterion("totalnum not between", value1, value2, "totalnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumIsNull() {
			addCriterion("logistnum is null");
			return (Criteria) this;
		}

		public Criteria andLogistnumIsNotNull() {
			addCriterion("logistnum is not null");
			return (Criteria) this;
		}

		public Criteria andLogistnumEqualTo(String value) {
			addCriterion("logistnum =", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumNotEqualTo(String value) {
			addCriterion("logistnum <>", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumGreaterThan(String value) {
			addCriterion("logistnum >", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumGreaterThanOrEqualTo(String value) {
			addCriterion("logistnum >=", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumLessThan(String value) {
			addCriterion("logistnum <", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumLessThanOrEqualTo(String value) {
			addCriterion("logistnum <=", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumLike(String value) {
			addCriterion("logistnum like", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumNotLike(String value) {
			addCriterion("logistnum not like", value, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumIn(List<String> values) {
			addCriterion("logistnum in", values, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumNotIn(List<String> values) {
			addCriterion("logistnum not in", values, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumBetween(String value1, String value2) {
			addCriterion("logistnum between", value1, value2, "logistnum");
			return (Criteria) this;
		}

		public Criteria andLogistnumNotBetween(String value1, String value2) {
			addCriterion("logistnum not between", value1, value2, "logistnum");
			return (Criteria) this;
		}

		public Criteria andPlatsourceIsNull() {
			addCriterion("platsource is null");
			return (Criteria) this;
		}

		public Criteria andPlatsourceIsNotNull() {
			addCriterion("platsource is not null");
			return (Criteria) this;
		}

		public Criteria andPlatsourceEqualTo(String value) {
			addCriterion("platsource =", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceNotEqualTo(String value) {
			addCriterion("platsource <>", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceGreaterThan(String value) {
			addCriterion("platsource >", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceGreaterThanOrEqualTo(String value) {
			addCriterion("platsource >=", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceLessThan(String value) {
			addCriterion("platsource <", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceLessThanOrEqualTo(String value) {
			addCriterion("platsource <=", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceLike(String value) {
			addCriterion("platsource like", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceNotLike(String value) {
			addCriterion("platsource not like", value, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceIn(List<String> values) {
			addCriterion("platsource in", values, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceNotIn(List<String> values) {
			addCriterion("platsource not in", values, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceBetween(String value1, String value2) {
			addCriterion("platsource between", value1, value2, "platsource");
			return (Criteria) this;
		}

		public Criteria andPlatsourceNotBetween(String value1, String value2) {
			addCriterion("platsource not between", value1, value2, "platsource");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andLasttimeIsNull() {
			addCriterion("lasttime is null");
			return (Criteria) this;
		}

		public Criteria andLasttimeIsNotNull() {
			addCriterion("lasttime is not null");
			return (Criteria) this;
		}

		public Criteria andLasttimeEqualTo(Date value) {
			addCriterion("lasttime =", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeNotEqualTo(Date value) {
			addCriterion("lasttime <>", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeGreaterThan(Date value) {
			addCriterion("lasttime >", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lasttime >=", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeLessThan(Date value) {
			addCriterion("lasttime <", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeLessThanOrEqualTo(Date value) {
			addCriterion("lasttime <=", value, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeIn(List<Date> values) {
			addCriterion("lasttime in", values, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeNotIn(List<Date> values) {
			addCriterion("lasttime not in", values, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeBetween(Date value1, Date value2) {
			addCriterion("lasttime between", value1, value2, "lasttime");
			return (Criteria) this;
		}

		public Criteria andLasttimeNotBetween(Date value1, Date value2) {
			addCriterion("lasttime not between", value1, value2, "lasttime");
			return (Criteria) this;
		}

		public Criteria andDelivercodeIsNull() {
			addCriterion("delivercode is null");
			return (Criteria) this;
		}

		public Criteria andDelivercodeIsNotNull() {
			addCriterion("delivercode is not null");
			return (Criteria) this;
		}

		public Criteria andDelivercodeEqualTo(String value) {
			addCriterion("delivercode =", value, "delivercode");
			return (Criteria) this;
		}

		public Criteria andDelivercodeNotEqualTo(String value) {
			addCriterion("delivercode <>", value, "delivercode");
			return (Criteria) this;
		}

		public Criteria andDelivercodeGreaterThan(String value) {
			addCriterion("delivercode >", value, "delivercode");
			return (Criteria) this;
		}

		public Criteria andDelivercodeGreaterThanOrEqualTo(String value) {
			addCriterion("delivercode >=", value, "delivercode");
			return (Criteria) this;
		}

		public Criteria andDelivercodeLessThan(String value) {
			addCriterion("delivercode <", value, "delivercode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_1001
	 * 
	 * @mbggenerated do_not_delete_during_merge Fri Jun 19 16:02:41 CST 2015
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table shop_order_1001
	 * 
	 * @mbggenerated Fri Jun 19 16:02:41 CST 2015
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}