package com.gsccs.b2c.plat.deliver.dao;

import com.gsccs.b2c.plat.deliver.model.Templet;
import com.gsccs.b2c.plat.deliver.model.TempletExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DeliverSetMapper {

	int countByExample(TempletExample example);

	int deleteByExample(TempletExample example);

	int deleteByPrimaryKey(String id);

	int insert(Templet record);

	int insertSelective(Templet record);

	List<Templet> selectByExample(TempletExample example);

	List<Templet> selectPageByExample(TempletExample example);

	Templet selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Templet record,
			@Param("example") TempletExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	int updateByExample(@Param("record") Templet record,
			@Param("example") TempletExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	int updateByPrimaryKeySelective(Templet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table plat_deliver_type
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	int updateByPrimaryKey(Templet record);

	long selectMaxId();
}