package com.gsccs.b2c.plat.seller.dao;

import com.gsccs.b2c.plat.seller.model.SellerPay;
import com.gsccs.b2c.plat.seller.model.SellerPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int countByExample(SellerPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int deleteByExample(SellerPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int insert(SellerPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int insertSelective(SellerPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    List<SellerPay> selectByExample(SellerPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    SellerPay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") SellerPay record, @Param("example") SellerPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByExample(@Param("record") SellerPay record, @Param("example") SellerPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByPrimaryKeySelective(SellerPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByPrimaryKey(SellerPay record);
}