package com.gsccs.b2c.plat.seller.dao;

import com.gsccs.b2c.plat.seller.model.StorePay;
import com.gsccs.b2c.plat.seller.model.StorePayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StorePayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int countByExample(StorePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int deleteByExample(StorePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int insert(StorePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int insertSelective(StorePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    List<StorePay> selectByExample(StorePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    StorePay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") StorePay record, @Param("example") StorePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByExample(@Param("record") StorePay record, @Param("example") StorePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByPrimaryKeySelective(StorePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_pay_store
     *
     * @mbggenerated Sat Aug 08 17:08:21 CST 2015
     */
    int updateByPrimaryKey(StorePay record);
}