package com.gsccs.b2c.plat.shop.dao;

import com.gsccs.b2c.plat.shop.model.BuyerLevelT;
import com.gsccs.b2c.plat.shop.model.BuyerLevelTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyerLevelTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int countByExample(BuyerLevelTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int deleteByExample(BuyerLevelTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int insert(BuyerLevelT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int insertSelective(BuyerLevelT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    List<BuyerLevelT> selectByExample(BuyerLevelTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    BuyerLevelT selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") BuyerLevelT record, @Param("example") BuyerLevelTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int updateByExample(@Param("record") BuyerLevelT record, @Param("example") BuyerLevelTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int updateByPrimaryKeySelective(BuyerLevelT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_buyer_level
     *
     * @mbggenerated Wed Apr 15 09:50:45 CST 2015
     */
    int updateByPrimaryKey(BuyerLevelT record);
}