package com.gsccs.b2c.plat.shop.dao;

import com.gsccs.b2c.plat.shop.model.SpecVal;
import com.gsccs.b2c.plat.shop.model.SpecValExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecValMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int countByExample(SpecValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int deleteByExample(SpecValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int insert(SpecVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int insertSelective(SpecVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    List<SpecVal> selectByExample(SpecValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    SpecVal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") SpecVal record, @Param("example") SpecValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int updateByExample(@Param("record") SpecVal record, @Param("example") SpecValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int updateByPrimaryKeySelective(SpecVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_spec_vals
     *
     * @mbggenerated Mon Mar 16 15:17:19 CST 2015
     */
    int updateByPrimaryKey(SpecVal record);
}