package com.gsccs.b2c.plat.shop.dao;

import com.gsccs.b2c.plat.shop.model.StoreCate;
import com.gsccs.b2c.plat.shop.model.StoreCateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int countByExample(StoreCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int deleteByExample(StoreCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int deleteByPrimaryKey(Long siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int insert(StoreCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int insertSelective(StoreCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    List<StoreCate> selectByExample(StoreCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    StoreCate selectByPrimaryKey(Long siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") StoreCate record, @Param("example") StoreCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int updateByExample(@Param("record") StoreCate record, @Param("example") StoreCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int updateByPrimaryKeySelective(StoreCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_cate
     *
     * @mbggenerated Mon Apr 13 15:50:25 CST 2015
     */
    int updateByPrimaryKey(StoreCate record);
}