package com.gsccs.b2c.plat.shop.dao;

import com.gsccs.b2c.plat.shop.model.StoreNavT;
import com.gsccs.b2c.plat.shop.model.StoreNavTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int countByExample(StoreNavTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int deleteByExample(StoreNavTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int insert(StoreNavT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int insertSelective(StoreNavT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    List<StoreNavT> selectByExample(StoreNavTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    StoreNavT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") StoreNavT record, @Param("example") StoreNavTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int updateByExample(@Param("record") StoreNavT record, @Param("example") StoreNavTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int updateByPrimaryKeySelective(StoreNavT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_store_nav
     *
     * @mbggenerated Wed Jun 24 16:46:49 CST 2015
     */
    int updateByPrimaryKey(StoreNavT record);
}