package com.gsccs.b2c.plat.shop.dao;

import com.gsccs.b2c.plat.shop.model.Type;
import com.gsccs.b2c.plat.shop.model.TypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	int countByExample(TypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	int deleteByExample(TypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	int insert(Type record);

	int insertSelective(Type record);

	List<Type> selectByExample(TypeExample example);

	List<Type> selectPageByExample(TypeExample example);

	Type selectByPrimaryKey(Long id);

	int updateByExampleSelective(@Param("record") Type record,
			@Param("example") TypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	int updateByExample(@Param("record") Type record,
			@Param("example") TypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shop_type
	 * 
	 * @mbggenerated Mon Mar 16 15:17:19 CST 2015
	 */
	int updateByPrimaryKey(Type record);
}