package com.gsccs.eb.api.domain.deliver;

import com.gsccs.b2c.api.APIConst;
import com.gsccs.eb.api.domain.base.Domain;

public class Templet extends Domain{
	
	/**
	 * 配送方式对象
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String title;
	private String corpid;
	private String hascod;
	private Integer firstunit;
	private Integer continueunit;
	private Float firstprice;
	private Float continueprice;
	private String expressions;
	private String protect;
	private Float protectRate;
	private Float minprice;
	private String setting;
	private String content;
	private String ordernum;
	private String status;
	private Long siteid;

	/**
	 * 类型的显示方式 0==货到付款 1==先收款后发货
	 */
	private String hascodStr;
	
	
	/**
	 * 配送方式 状态。。1 开启。0 关闭
	 */
	private String statusStr;
	
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.id
	 * 
	 * @param id
	 *            the value for plat_deliver_type.id
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.title
	 * 
	 * @return the value of plat_deliver_type.title
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.title
	 * 
	 * @param title
	 *            the value for plat_deliver_type.title
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.corpid
	 * 
	 * @return the value of plat_deliver_type.corpid
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public String getCorpid() {
		return corpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.corpid
	 * 
	 * @param corpid
	 *            the value for plat_deliver_type.corpid
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setCorpid(String corpid) {
		this.corpid = corpid == null ? null : corpid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.hascod
	 * 
	 * @return the value of plat_deliver_type.hascod
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public String getHascod() {
		return hascod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.hascod
	 * 
	 * @param hascod
	 *            the value for plat_deliver_type.hascod
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setHascod(String hascod) {
		this.hascod = hascod == null ? null : hascod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.firstunit
	 * 
	 * @return the value of plat_deliver_type.firstunit
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public Integer getFirstunit() {
		return firstunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.firstunit
	 * 
	 * @param firstunit
	 *            the value for plat_deliver_type.firstunit
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setFirstunit(Integer firstunit) {
		this.firstunit = firstunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.continueunit
	 * 
	 * @return the value of plat_deliver_type.continueunit
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public Integer getContinueunit() {
		return continueunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.continueunit
	 * 
	 * @param continueunit
	 *            the value for plat_deliver_type.continueunit
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setContinueunit(Integer continueunit) {
		this.continueunit = continueunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.firstprice
	 * 
	 * @return the value of plat_deliver_type.firstprice
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public Float getFirstprice() {
		return firstprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.firstprice
	 * 
	 * @param firstprice
	 *            the value for plat_deliver_type.firstprice
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setFirstprice(Float firstprice) {
		this.firstprice = firstprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.continueprice
	 * 
	 * @return the value of plat_deliver_type.continueprice
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public Float getContinueprice() {
		return continueprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.continueprice
	 * 
	 * @param continueprice
	 *            the value for plat_deliver_type.continueprice
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setContinueprice(Float continueprice) {
		this.continueprice = continueprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column plat_deliver_type.expressions
	 * 
	 * @return the value of plat_deliver_type.expressions
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public String getExpressions() {
		return expressions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column plat_deliver_type.expressions
	 * 
	 * @param expressions
	 *            the value for plat_deliver_type.expressions
	 * 
	 * @mbggenerated Fri Jun 05 14:47:54 CST 2015
	 */
	public void setExpressions(String expressions) {
		this.expressions = expressions == null ? null : expressions.trim();
	}

	public String getProtect() {
		return protect;
	}

	public void setProtect(String protect) {
		this.protect = protect == null ? null : protect.trim();
	}

	public Float getProtectRate() {
		return protectRate;
	}

	
	public void setProtectRate(Float protectRate) {
		this.protectRate = protectRate;
	}

	public Float getMinprice() {
		return minprice;
	}

	
	public void setMinprice(Float minprice) {
		this.minprice = minprice;
	}

	public String getSetting() {
		return setting;
	}

	public void setSetting(String setting) {
		this.setting = setting == null ? null : setting.trim();
	}

	
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	
	public String getOrdernum() {
		return ordernum;
	}

	
	public void setOrdernum(String ordernum) {
		this.ordernum = ordernum == null ? null : ordernum.trim();
	}

	
	public String getStatus() {
		return status;
	}

	
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	
	public Long getSiteid() {
		return siteid;
	}

	
	public void setSiteid(Long siteid) {
		this.siteid = siteid;
	}
	
	//是否保价
	public boolean isProtectPrice(){
		if(null == getProtect()){
			return false;
		}
		if (getProtect().equals("1")){
			return true;
		}
		return false;
	}

	public String getHascodStr() {
		if (hascod.equals(APIConst.DELIVERTYPE_HASCOD_COD_OK)) {
			hascodStr ="是";
		}else if(hascod.equals(APIConst.DELIVERTYPE_HASCOD_COD_OK)){
			hascodStr ="否";
		}
		return hascodStr;
	}

	public void setHascodStr(String hascodStr) {
		this.hascodStr = hascodStr;
	}

	public String getStatusStr() {
		if (status.equals(APIConst.DELIVERTYPE_STATUS_OK)) {
			statusStr ="启用";
		}else if(status.equals(APIConst.DELIVERTYPE_STATUS_NO)){
			statusStr ="关闭";
		}
		return statusStr;
	}

	public void setStatusStr(String statusStr) {
		this.statusStr = statusStr;
	}
	
	
}